import { useState } from "react";

type Props = {
  values: Record<string, string>;
  resultOutput: string;
};

export function DesVisualizer({ values, resultOutput }: Props) {
  const [selectedSubstep, setSelectedSubstep] = useState<"split" | "expansion" | "keyxor" | "sbox" | "pbox" | "swap">("sbox");

  const substeps = {
    split: {
      title: "1. 32-bit L/R Split",
      math: "Block (64-bit) → L₀ (32-bit) || R₀ (32-bit)",
      detail: "The 64-bit plaintext is first permuted by the Initial Permutation (IP) and split into 32-bit left half L and right half R.",
    },
    expansion: {
      title: "2. Expansion Permutation E",
      math: "E(R_{i-1}) : 32-bit → 48-bit",
      detail: "Expands the 32-bit right half by replicating 16 boundary bits into a 48-bit vector matching the subkey size.",
    },
    keyxor: {
      title: "3. Round Key Mixing (XOR)",
      math: "E(R_{i-1}) ⊕ K_i (48-bit)",
      detail: "Bitwise XOR of the expanded 48-bit vector with the 48-bit round subkey generated by the 56-bit key schedule.",
    },
    sbox: {
      title: "4. Eight Non-linear S-Boxes (S₁–S₈)",
      math: "S(6-bit) → 4-bit (48-bit total → 32-bit)",
      detail: "The only non-linear component of DES. 8 substitution tables compress 6-bit chunks into 4-bit chunks, defeating linear cryptanalysis.",
    },
    pbox: {
      title: "5. Permutation P",
      math: "P(32-bit) → 32-bit diffusion",
      detail: "A fixed 32-bit permutation that distributes the 4 output bits of each S-box across 4 different S-boxes in the next round.",
    },
    swap: {
      title: "6. Feistel Cross & XOR",
      math: "L_i = R_{i-1} ; R_i = L_{i-1} ⊕ F(R_{i-1}, K_i)",
      detail: "The right half becomes the next left half. The next right half is L_{i-1} XORed with the round function F output.",
    },
  };

  const cur = substeps[selectedSubstep];

  return (
    <div className="rounded-[18px] bg-background/80 p-4 ring-1 ring-border/80">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border/70 pb-3">
        <div>
          <span className="text-[10.5px] uppercase tracking-wider text-primary font-medium">DES Horst Feistel Cipher Architecture</span>
          <p className="text-[12px] text-muted-foreground">
            Symmetric Involutive Network · 16 Rounds · 64-bit Block / 56-bit Key
          </p>
        </div>
      </div>

      {/* Interactive Substep Selector */}
      <div className="mt-3.5 flex flex-wrap gap-1.5">
        {(Object.keys(substeps) as Array<keyof typeof substeps>).map((key) => (
          <button
            key={key}
            type="button"
            onClick={() => setSelectedSubstep(key)}
            className={`rounded-[10px] px-2.5 py-1.5 text-[11.5px] font-medium transition ${
              selectedSubstep === key
                ? "bg-primary text-primary-foreground shadow-2xs font-semibold"
                : "bg-card text-muted-foreground ring-1 ring-border hover:bg-muted"
            }`}
          >
            {substeps[key].title.split(". ")[1]}
          </button>
        ))}
      </div>

      {/* Substep Description */}
      <div className="mt-4 rounded-[14px] bg-card p-3.5 ring-1 ring-border shadow-2xs">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <span className="font-display text-[13.5px] font-semibold text-foreground">{cur.title}</span>
          <code className="rounded bg-background px-2 py-0.5 font-mono text-[11px] text-primary ring-1 ring-border">
            {cur.math}
          </code>
        </div>
        <p className="mt-1 text-[12px] leading-relaxed text-muted-foreground">{cur.detail}</p>
      </div>

      {/* Visual Feistel Flowchart */}
      <div className="mt-4 flex flex-col items-center">
        <span className="label-tiny mb-2">Feistel Round i Structure:</span>
        <div className="w-full max-w-md rounded-[16px] bg-card p-4 ring-1 ring-border shadow-xs font-mono text-[11px]">
          {/* Top Halves */}
          <div className="flex justify-between gap-4">
            <div className="flex-1 rounded-[10px] bg-background p-2 text-center ring-1 ring-border font-bold">
              L_(i-1) [32 bits]
            </div>
            <div className="flex-1 rounded-[10px] bg-primary/15 p-2 text-center ring-1 ring-primary/30 font-bold text-primary">
              R_(i-1) [32 bits]
            </div>
          </div>

          {/* Flow Arrows */}
          <div className="my-2 flex justify-between px-8 text-muted-foreground">
            <span>↓</span>
            <span>↓ enters F(R, K)</span>
          </div>

          {/* Round Function Box */}
          <div className="rounded-[12px] bg-background p-2.5 ring-1 ring-border">
            <div className="flex items-center justify-between text-[10px] text-muted-foreground border-b border-border/60 pb-1">
              <span>ROUND FUNCTION F</span>
              <span>Subkey K_i [48 bits]</span>
            </div>
            <div className="mt-1.5 flex items-center justify-around gap-1 text-[10.5px]">
              <span className="rounded bg-card px-1.5 py-0.5 ring-1 ring-border">E (32→48)</span>
              <span>⊕</span>
              <span className="rounded bg-primary/10 px-1.5 py-0.5 text-primary ring-1 ring-primary/20 font-bold">8 S-Boxes (48→32)</span>
              <span>→</span>
              <span className="rounded bg-card px-1.5 py-0.5 ring-1 ring-border">P (32)</span>
            </div>
          </div>

          {/* XOR with L */}
          <div className="my-2 flex justify-between px-8 text-muted-foreground">
            <span>⊕ (XOR with F output)</span>
            <span>swaps to L_i ↘</span>
          </div>

          {/* Bottom Halves */}
          <div className="flex justify-between gap-4">
            <div className="flex-1 rounded-[10px] bg-primary/15 p-2 text-center ring-1 ring-primary/30 font-bold text-primary">
              L_i = R_(i-1)
            </div>
            <div className="flex-1 rounded-[10px] bg-background p-2 text-center ring-1 ring-border font-bold">
              R_i = L_(i-1) ⊕ F
            </div>
          </div>
        </div>
      </div>

      {/* Feistel Involutive Property Insight */}
      <div className="mt-4 rounded-[10px] bg-card/60 p-2.5 text-[11.5px] text-muted-foreground ring-1 ring-border/60">
        <strong className="text-foreground">Feistel Involutory Insight (Stallings Ch. 4):</strong> Decryption uses the exact same circuit structure as encryption; simply apply the round keys in reverse order ($K_{16}, K_{15}, \dots, K_1$). The round function $F$ does not even need to be mathematically invertible!
      </div>
    </div>
  );
}
