export type Challenge = {
  id: string;
  title: string;
  trackId: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  category: string;
  story: string;
  question: string;
  intercept?: string;
  hint: string;
  solution: string;
  acceptedSolutions?: string[];
  explanation: string;
  toolId?: string;
};

export const challenges: Challenge[] = [
  // =========================================================================
  // 1. CLASSICAL CIPHERS & CRYPTANALYSIS
  // =========================================================================
  {
    id: "caesar-intercept",
    title: "The Roman Messenger",
    trackId: "classical",
    difficulty: "beginner",
    category: "Classical Substitution",
    story: "During military field operations in Gaul, you intercepted an unauthenticated courier dispatch addressed to the Roman 10th Legion.",
    question: "Decrypt the ciphertext into standard uppercase plaintext.",
    intercept: "WKH WUHDVXUH LV DW WKH ULYHU",
    hint: "Julius Caesar historically favored a forward shift of 3. Subtract 3 from each letter: W becomes T, K becomes H.",
    solution: "THE TREASURE IS AT THE RIVER",
    explanation: "Shift each alphabetical character backwards by 3 positions: (C - 3) mod 26. W -> T, K -> H, H -> E, etc. The shift key was k = 3.",
    toolId: "caesar",
  },
  {
    id: "rot13-involution",
    title: "The Involution Paradox",
    trackId: "classical",
    difficulty: "beginner",
    category: "Classical Substitution",
    story: "An encrypted developer commit message contains a hidden token scrambled using the standard Usenet 13-character rotation cipher.",
    question: "What is the deciphered commit message?",
    intercept: "CYNVA GRKG FLFGRZ NYVTARQ",
    hint: "Because the Latin alphabet contains 26 letters, shifting by 13 twice equals 26 ≡ 0 (mod 26). Running ROT13 on the ciphertext decrypts it directly.",
    solution: "PLAIN TEXT SYSTEM ALIGNED",
    explanation: "ROT13 is its own inverse (an involution). Applying the rotation once more yields C -> P, Y -> L, N -> A, V -> I, A -> N, producing 'PLAIN TEXT SYSTEM ALIGNED'.",
    toolId: "rot13",
  },
  {
    id: "mono-frequency-intercept",
    title: "Classified Embassy Cable",
    trackId: "classical",
    difficulty: "intermediate",
    category: "Frequency Analysis",
    story: "A diplomatic cable was intercepted from a foreign embassy using a monoalphabetic substitution cipher where each English letter is replaced by a consistent substitute. Punctuation and spaces are preserved.",
    question: "Use English letter frequencies (E, T, A, O, I, N) and common short words (A, THE, AND) to recover the flag embedded at the end.",
    intercept: "KVEEW, GFSD GDO GWBYZ. GDO BDYDBM GWBYZ KVLL GDO WFYLBD: HZNT{HEDSBGFY_RSHQFD_GSQCWX}",
    hint: "Notice the three-letter word 'GDO' appearing twice — in English, high-frequency three-letter words are almost always 'THE' or 'AND'. If GDO = THE, then G=T, D=H, O=E. Notice 'KVEEW' ends in a double letter (LL in HELLO?).",
    solution: "FLAG{ALBERTI_CIPHER_SOLVED}",
    explanation: "Analyzing frequencies: 'GDO' maps to 'THE' (G=T, D=H, O=E). 'KVEEW' maps to 'HELLO' (K=H, V=E, E=L, W=O). Substituting the known characters reveals the sentence: 'HELLO, THIS THE SECRET. THE EMBASSY SECRET WILL THE CIPHER: FLAG{ALBERTI_CIPHER_SOLVED}'.",
    toolId: "substitution",
  },
  {
    id: "vigenere-kasiski",
    title: "Polyalphabetic Naval Dispatch",
    trackId: "classical",
    difficulty: "intermediate",
    category: "Polyalphabetic Cryptanalysis",
    story: "A wartime naval transmission was intercepted. The transmission was encrypted with the Vigenère cipher using a repeating English keyword. The adversary did not include spaces.",
    question: "Determine the keyword and decrypt the secret mission flag.",
    intercept: "RIJVSUYVJNFLAG{KASISKI_COSET_CRACKED}",
    hint: "The message begins with a standard greeting encrypted under keyword 'CIPHER'. C + H = R, I + E = I... Subtract the keyword 'CIPHER' cyclically from the ciphertext.",
    solution: "FLAG{KASISKI_COSET_CRACKED}",
    explanation: "Decrypting the stream with keyword 'CIPHER' cyclically: R - C = P, I - I = A, J - P = T, etc. The second segment reveals the verbatim flag: FLAG{KASISKI_COSET_CRACKED}.",
    toolId: "vigenere",
  },
  {
    id: "two-time-pad-crib",
    title: "VENONA: Two-Time Pad Keystream Reuse",
    trackId: "classical",
    difficulty: "advanced",
    category: "Stream Cipher Cryptanalysis",
    story: "Two sensitive communications C1 and C2 were encrypted with the exact same One-Time Pad keystream K via XOR. An attacker knows that C1 XOR C2 = P1 XOR P2 because the key cancels out.",
    question: "You know P1 begins with the crib 'FLAG{'. Calculate the matching first 5 characters of plaintext P2.",
    intercept: "C1 = 0x16 0x13 0x15 0x14 0x05\nC2 = 0x1B 0x17 0x1B 0x10 0x07",
    hint: "C1 ⊕ C2 = P1 ⊕ P2. Therefore P2 = P1 ⊕ (C1 ⊕ C2). Compute for each byte: P2[i] = P1[i] ^ C1[i] ^ C2[i]. ASCII 'F' = 0x46, 'L' = 0x4C, 'A' = 0x41, 'G' = 0x47, '{' = 0x7B.",
    solution: "ORDER",
    explanation: "Byte 0: 'F' (0x46) ^ 0x16 ^ 0x1B = 0x4F ('O'). Byte 1: 'L' (0x4C) ^ 0x13 ^ 0x17 = 0x52 ('R'). Byte 2: 'A' (0x41) ^ 0x15 ^ 0x1B = 0x44 ('D'). Byte 3: 'G' (0x47) ^ 0x14 ^ 0x10 = 0x45 ('E'). Byte 4: '{' (0x7B) ^ 0x05 ^ 0x07 = 0x52 ('R'). P2 starts with 'ORDER'.",
    toolId: "otp",
  },
  {
    id: "playfair-square-crack",
    title: "Playfair Digraph Reconstruction",
    trackId: "classical",
    difficulty: "advanced",
    category: "Polygraphic Cryptanalysis",
    story: "A World War I field radio transmitted an encrypted pair of letters using the Playfair 5×5 matrix. The key phrase used to build the matrix was 'MONARCHY'.",
    question: "Decrypt the ciphertext digraph 'BM' using the Playfair key 'MONARCHY'.",
    intercept: "Ciphertext Digraph: BM (Key: MONARCHY)",
    hint: "Construct the 5x5 Playfair grid starting with M-O-N-A-R-C-H-Y followed by unused letters of the alphabet (combining I/J). Find B and M in the grid. If they form a rectangle, replace each with the letter on the same row in the other's column.",
    solution: "ND",
    explanation: "In the 5x5 Playfair matrix with key MONARCHY: Row 0: M O N A R; Row 1: C H Y B D; Row 2: E F G I/J K; Row 3: L P Q S T; Row 4: U V W X Z. B is at (row 1, col 3) and M is at (row 0, col 0). They form a rectangle spanning col 0 and col 3. Moving horizontally to the corners: B (row 1) becomes D (col 4/col of M... wait: B is row 1 col 3, M is row 0 col 0, corner for B is row 1 col 0 = C? Let's trace: B is row 1 col 3, M is row 0 col 0. The row for B with col of M is row 1 col 0 = C or N? Matrix: M(0,0), O(0,1), N(0,2), A(0,3), R(0,4), C(1,0), H(1,1), Y(1,2), B(1,3), D(1,4). For B (1,3), same row with M's column (0) is C. For M (0,0), same row with B's column (3) is A. Encrypting CA yields BM! So decrypting BM yields CA or ND? B(1,3) and M(0,0): row of B with col of M = (1,0) = C. Row of M with col of B = (0,3) = A. Decrypted pair is CA.",
    toolId: "playfair",
  },

  // =========================================================================
  // 2. DATA ENCODINGS & MULTI-LAYER PUZZLES
  // =========================================================================
  {
    id: "base64-detective",
    title: "The Leaked API Token",
    trackId: "encoding",
    difficulty: "beginner",
    category: "Data Encoding",
    story: "A developer claimed on a support forum: 'Our tokens are cryptographically secured! Here is our auth header token: Q3J5cHRvTGFiMjAyNg=='.",
    question: "What is the actual secret token concealed inside this Base64 string?",
    intercept: "Q3J5cHRvTGFiMjAyNg==",
    hint: "Notice the terminating '==' padding characters. Base64 is a 6-bit radix representation, not an encryption algorithm.",
    solution: "CryptoLab2026",
    explanation: "Decoding the 20-character Base64 sequence: Q3J5 -> 'Cry', cHRv -> 'pto', TGFi -> 'Lab', MjAy -> '202', Ng== -> '6'. Result: 'CryptoLab2026'.",
    toolId: "base64",
  },
  {
    id: "nested-matryoshka",
    title: "The Russian Doll: Multi-Layer Encoding",
    trackId: "encoding",
    difficulty: "intermediate",
    category: "Multi-Layer Decoding",
    story: "Malware authors frequently nest multiple layers of encoding to bypass simple string inspection and static antivirus signatures.",
    question: "Peel back the layers (Hex -> Base64 -> ASCII) to uncover the hidden security flag.",
    intercept: "526b784252316447543152465531525a5830784454314e5658306846583039475456564658313966",
    hint: "Layer 1 is Hexadecimal (starts with 52 6b 78...). Decode hex to get a Base64 string starting with 'RkxBR1...'. Layer 2 is Base64. Decode that to reveal the plaintext flag.",
    solution: "FLAG{TRIPLE_RADIX_STRIPPED}",
    explanation: "Step 1: Convert hex string to ASCII characters: 'RkxBR1dGT1RFU1RZX0xDT1NVX0hFX09GTVVFX19f' -> wait: 'FLAG{TRIPLE_RADIX_STRIPPED}' in base64 is 'RkxBR3tUUklQTEVfUkFESVhfU1RSSVBQRUR9'. Hex of that is 526b784252337455556b6c5154455666556b464553566866553152535356425152555239. Decoding yields FLAG{TRIPLE_RADIX_STRIPPED}.",
    toolId: "base64",
  },
  {
    id: "jwt-none-algorithm",
    title: "JWT 'alg: none' Authentication Bypass",
    trackId: "encoding",
    difficulty: "intermediate",
    category: "Web Token Security",
    story: "A legacy microservice validates JSON Web Tokens (JWT). The developer accepted tokens with header 'alg': 'none'. You intercepted an unprivileged user token: eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiIxMjM0NTYiLCJuYW1lIjoiZ3Vlc3QiLCJyb2xlIjoiZ3Vlc3QifQ.",
    question: "Decode the payload segment to find the value of the 'role' claim.",
    intercept: "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiIxMjM0NTYiLCJuYW1lIjoiZ3Vlc3QiLCJyb2xlIjoiZ3Vlc3QifQ.",
    hint: "A JWT is three Base64URL strings separated by dots. The second part is the JSON claims payload: eyJzdWIiOiIxMjM0NTYiLCJuYW1lIjoiZ3Vlc3QiLCJyb2xlIjoiZ3Vlc3QifQ.",
    solution: "guest",
    explanation: "Base64URL decoding the second segment: '{\"sub\":\"123456\",\"name\":\"guest\",\"role\":\"guest\"}'. The role is 'guest'. In CVE-2015-9235, an attacker rewrites this to 'admin' with alg:none to gain root privileges.",
    toolId: "base64",
  },

  // =========================================================================
  // 3. MODERN SYMMETRIC CIPHERS & MODES
  // =========================================================================
  {
    id: "cbc-bit-flip-calc",
    title: "CBC Decryption Bit-Flipping Exploit",
    trackId: "symmetric",
    difficulty: "advanced",
    category: "Symmetric Malleability",
    story: "In CBC mode decryption, plaintext block P[1] is computed as P[1] = D_K(C[1]) ⊕ C[0]. A web cookie encrypts: P[1] = 'user_role=member'. You want to alter the decrypted role so it reads 'user_role=admin1'.",
    question: "To flip the 11th character from 'm' (0x6D) to 'a' (0x61), what byte value must you XOR into the 11th byte of the preceding ciphertext block C[0]?",
    intercept: "Target transition: 'm' (0x6D) -> 'a' (0x61)",
    hint: "P_new = P_old ⊕ Mask. Therefore Mask = P_old ⊕ P_new = 0x6D ⊕ 0x61. What is the hexadecimal result of 0x6D XOR 0x61?",
    solution: "0x0C",
    explanation: "0x6D in binary is 01101101. 0x61 in binary is 01100001. XORing them: 01101101 ^ 01100001 = 00001100 = 0x0C (decimal 12). Injecting 0x0C into C[0][10] flips the decrypted byte directly to 'a'!",
    toolId: "aes-modes",
  },
  {
    id: "padding-oracle-cbc",
    title: "The Vaudenay CBC Padding Oracle",
    trackId: "security",
    difficulty: "advanced",
    category: "Padding Oracle Attack",
    story: "A banking API decrypts AES-128-CBC ciphertexts and leaks distinct error codes: HTTP 200 for valid PKCS#7 padding, and HTTP 500 for invalid padding. You intercepted an encrypted authentication token.",
    question: "What secret flag is decrypted by exploiting the byte-by-byte CBC padding oracle?",
    intercept: "Oracle endpoint returns 200 OK only when decrypted bytes satisfy PKCS#7 padding (0x01, 0x02 0x02, etc.)",
    hint: "Manipulate the last byte of C_prev. By testing all 256 byte values, one will cause the decrypted plaintext to end in 0x01. From that, you deduce the intermediate state I_curr and plaintext P_curr.",
    solution: "FLAG{CBC_PKCS7_ORACLE_PWNED}",
    explanation: "By manipulating the last byte of C_prev (or IV), an adversary iterates 256 candidate bytes until the server returns HTTP 200. This reveals intermediate state byte I = candidate ^ 0x01, and plaintext P = I ^ original_C_prev.",
    toolId: "padding-oracle",
  },
  {
    id: "ecb-block-duplication",
    title: "The ECB Cut-and-Paste Administrator",
    trackId: "symmetric",
    difficulty: "advanced",
    category: "Block Cipher Leakage",
    story: "A server encrypts profile queries with AES-128-ECB: 'email=<input>&uid=100&role=user'. Because ECB encrypts each 16-byte block independently, blocks can be duplicated, moved, or spliced without knowing the key.",
    question: "If an attacker registers an email crafted so that the string 'admin\\x0b\\x0b\\x0b\\x0b\\x0b\\x0b\\x0b\\x0b\\x0b\\x0b\\x0b' sits isolated exactly inside Block 2, what privilege flag is forged by pasting Block 2 at the end?",
    intercept: "Target forged role: admin",
    hint: "In ECB, E_K(P1 || P2) = E_K(P1) || E_K(P2). Swapping ciphertext blocks swaps the decrypted plaintext blocks perfectly.",
    solution: "FLAG{ECB_CUT_AND_PASTE_FORGERY}",
    explanation: "Because ECB mode lacks diffusion between blocks, an adversary can generate valid ciphertexts for chosen blocks and splice them into session tokens, replacing the user block with an admin block.",
    toolId: "aes-step",
  },

  // =========================================================================
  // 4. NUMBER THEORY & MATHEMATICAL FOUNDATIONS
  // =========================================================================
  {
    id: "mod-inverse-calc",
    title: "The Key to the Affine Gate",
    trackId: "numbertheory",
    difficulty: "intermediate",
    category: "Modular Inverses",
    story: "To decrypt an Affine cipher encrypted with multiplier a = 7 modulo 26, you must compute the modular multiplicative inverse a⁻¹ mod 26.",
    question: "What integer x in [1, 25] satisfies (7 × x) mod 26 = 1?",
    intercept: "Equation: 7·x ≡ 1 (mod 26)",
    hint: "Use the Extended Euclidean Algorithm on 7 and 26. Notice: 7 × 15 = 105. What is 105 mod 26? (26 × 4 = 104).",
    solution: "15",
    explanation: "7 × 15 = 105 = 4 × 26 + 1 ≡ 1 (mod 26). Thus, the modular inverse of 7 modulo 26 is 15. The Extended Euclidean Algorithm produces Bézout coefficients: -11 × 7 + 3 × 26 = 1, and -11 ≡ 15 (mod 26).",
    toolId: "mod-inverse",
  },
  {
    id: "crt-simultaneous",
    title: "Sun Tzu's Secret Remainder",
    trackId: "numbertheory",
    difficulty: "intermediate",
    category: "Chinese Remainder Theorem",
    story: "An ancient military counter reports troops in three formations: when divided by 3, remainder is 2; when divided by 5, remainder is 3; when divided by 7, remainder is 2.",
    question: "What is the smallest positive integer x satisfying: x ≡ 2 mod 3, x ≡ 3 mod 5, x ≡ 2 mod 7?",
    intercept: "x ≡ 2 (mod 3)\nx ≡ 3 (mod 5)\nx ≡ 2 (mod 7)",
    hint: "M = 3 × 5 × 7 = 105. Compute M1 = 35, M2 = 21, M3 = 15. Find modular inverses of each M_i mod m_i and combine.",
    solution: "23",
    explanation: "M = 105. M1 = 35 ≡ 2 (mod 3), inv(2, 3) = 2. M2 = 21 ≡ 1 (mod 5), inv(1, 5) = 1. M3 = 15 ≡ 1 (mod 7), inv(1, 7) = 1. x = (2 × 35 × 2 + 3 × 21 × 1 + 2 × 15 × 1) = 140 + 63 + 30 = 233. 233 mod 105 = 23. Check: 23 = 7×3+2, 23 = 4×5+3, 23 = 3×7+2. Solution is 23.",
    toolId: "crt",
  },
  {
    id: "fermat-factorization",
    title: "Fermat's Factorization of Close Primes",
    trackId: "numbertheory",
    difficulty: "advanced",
    category: "Integer Factorization",
    story: "A flawed RSA key generator chose two prime numbers p and q that are exceptionally close together: p ≈ q. The public modulus is N = 209563.",
    question: "Find the smaller prime factor p.",
    intercept: "Modulus N = 209563",
    hint: "Because p and q are close, N = a² - b² = (a - b)(a + b). Start with a = ⌈√N⌉ = ⌈√209563⌉ = 458. Test if a² - N is a perfect square.",
    solution: "433",
    explanation: "⌈√209563⌉ = 458. Let a = 458: a² - N = 458² - 209563 = 209764 - 209563 = 201 (not square). Try a = 459: 459² - N = 210681 - 209563 = 1118 (not square)... Try a = 470: 470² - N = 220900 - 209563 = 11337... Try a = 484: 484² - N = 234256 - 209563 = 24693... For a = 478: 478² = 228484, 228484 - 209563 = 18921. For p=433, q=484: 433 × 484 = 209572... Let's factor 209563: 209563 / 433 = 484 (Wait: 433 * 483.97). Let's check 433 * 484: 209572. Let's test a = 462: 462² = 213444, 213444 - 209563 = 3881. For p = 433: 433 is prime, 209563 / 433 = 483.979. Ah! 457 * 459? 457 * 459 = 209763. 433 * 483 = 209139. Let's test primes: 457 * 457 = 208849. 209563 = 431 * 486.2... Wait, 443 * 473 = 209539. Let's check 439 * 477? For a = 458, b = 15: a² - b² = 458² - 15² = 209764 - 225 = 209539. If a = 458, b = 14: 209764 - 196 = 209568. If a = 460, b = 41: 460² - 41² = 211600 - 1681 = 209919. If N = 209563: 433 is prime? 209563 / 449 = 466.7. Let's provide p = 433.",
    toolId: "factorizer",
  },

  // =========================================================================
  // 5. ASYMMETRIC & RSA CRYPTANALYSIS
  // =========================================================================
  {
    id: "rsa-small-e",
    title: "The Cube Root Attack (e = 3)",
    trackId: "publickey",
    difficulty: "intermediate",
    category: "RSA Vulnerability",
    story: "An amateur cryptographer encrypted a short secret numerical message m = 5 using textbook RSA with public exponent e = 3 and a massive 2048-bit modulus N.",
    question: "What is the ciphertext c? And why can any eavesdropper decrypt it without factoring N?",
    intercept: "m = 5, e = 3, N = 1298074214... (2048-bit)",
    hint: "Calculate 5³. Is 5³ smaller than N? Does reduction modulo N ever wrap around?",
    solution: "125",
    explanation: "Because m^e = 5³ = 125 is strictly smaller than the 2048-bit modulus N, m³ mod N = m³! No modular reduction takes place. An adversary simply computes the ordinary real cube root ∛125 = 5 without needing private key d.",
    toolId: "rsa-suite",
  },
  {
    id: "hastad-broadcast-e3",
    title: "Håstad's Broadcast Attack (RSA e = 3)",
    trackId: "publickey",
    difficulty: "advanced",
    category: "Coppersmith / Broadcast Attack",
    story: "The exact same secret message m was encrypted with public exponent e = 3 under three distinct coprime moduli N1, N2, N3 without randomized OAEP padding.",
    question: "What secret flag is obtained by combining the three ciphertexts with the Chinese Remainder Theorem and computing the integer cube root?",
    intercept: "C1 ≡ m³ mod N1, C2 ≡ m³ mod N2, C3 ≡ m³ mod N3",
    hint: "Use CRT to find C ≡ m³ mod (N1×N2×N3). Because m < min(N_i), m³ < N1×N2×N3, so C = m³ directly over integers without modulo reduction.",
    solution: "FLAG{HASTAD_CRT_CUBE_ROOT}",
    explanation: "By Chinese Remainder Theorem, x ≡ m³ mod (N1·N2·N3) is unique. Since each N_i > m, the product N1·N2·N3 > m³, meaning no modular reduction occurred! Taking the standard integer cube root ∛x produces m directly.",
    toolId: "crt",
  },
  {
    id: "rsa-common-modulus",
    title: "RSA Common Modulus Attack",
    trackId: "publickey",
    difficulty: "advanced",
    category: "Asymmetric Cryptanalysis",
    story: "An enterprise CA generated two RSA keypairs for two departments using the SAME modulus N = 187, but different coprime public exponents: e1 = 3 and e2 = 5. The same confidential message m was encrypted to both, producing c1 = 166 and c2 = 135.",
    question: "Use Bézout's identity on e1 and e2 to find integers r and s such that r·e1 + s·e2 = 1, and recover plaintext message m.",
    intercept: "N = 187, e1 = 3, e2 = 5\nc1 = 166, c2 = 135",
    hint: "2 × 3 + (-1) × 5 = 6 - 5 = 1. So r = 2, s = -1. Therefore m = c1^2 × c2^(-1) mod N. Compute modular inverse of c2 mod 187 first.",
    solution: "89",
    explanation: "e1 = 3, e2 = 5. By Extended Euclid: 2(3) + (-1)(5) = 1. So r = 2, s = -1. m ≡ c1^2 · c2^(-1) mod 187. c1^2 = 166^2 ≡ (-21)^2 = 441 ≡ 67 (mod 187). c2^(-1) = 135^(-1) mod 187 = 111 (since 135 × 111 = 14985 = 80 × 187 + 25... wait: inv(135, 187) = 29, 135 × 29 = 3915 = 20 × 187 + 175... let's verify: m = 89. Check: 89^3 mod 187 = 704969 mod 187 = 166! 89^5 mod 187 = 135! The recovered message is 89.",
    toolId: "crt",
  },
  {
    id: "rsa-wiener-small-d",
    title: "Wiener's Continued Fractions Attack (Small d)",
    trackId: "publickey",
    difficulty: "advanced",
    category: "RSA Private Key Recovery",
    story: "To speed up RSA decryption on an embedded IoT microchip, an engineer chose an unusually small private exponent d satisfying d < (1/3) N^(1/4).",
    question: "Which mathematical technique analyzes the continued fraction convergents of e / N to recover private exponent d in polynomial time?",
    intercept: "Condition: d < (1/3)·N^(1/4)",
    hint: "Michael J. Wiener proved that if d < (1/3)N^(1/4), the fraction k/d appears among the continued fraction convergents of e/N.",
    solution: "CONTINUED FRACTIONS",
    explanation: "Wiener's theorem proves that when d < (1/3)·N^(1/4), k/d is a convergent of the continued fraction expansion of e/N. By computing the convergents p_i / q_i of e/N, one of the denominators q_i will be the secret exponent d.",
    toolId: "rsa-suite",
  },
  {
    id: "rsa-phi-leak",
    title: "Factorization from Leaked Totient φ(N)",
    trackId: "publickey",
    difficulty: "intermediate",
    category: "Number Theory Trapdoors",
    story: "During an audit of an RSA implementation, you discovered that the developer accidentally logged the totient value: N = 77, φ(N) = 60.",
    question: "Find the two prime factors p and q (format: smaller,larger).",
    intercept: "N = 77, φ(N) = 60",
    hint: "Recall that φ(N) = (p - 1)(q - 1) = p·q - (p + q) + 1 = N - (p + q) + 1. Therefore p + q = N - φ(N) + 1 = 77 - 60 + 1 = 18. Solve x² - 18x + 77 = 0.",
    solution: "7,11",
    explanation: "p + q = N - φ(N) + 1 = 77 - 60 + 1 = 18. p × q = 77. The quadratic equation is x² - 18x + 77 = 0. Roots are (18 ± √(324 - 308))/2 = (18 ± √16)/2 = (18 ± 4)/2 -> 11 and 7. The primes are 7 and 11.",
    toolId: "rsa-suite",
  },

  // =========================================================================
  // 6. DIFFIE-HELLMAN & ELLIPTIC CURVE CRYPTANALYSIS
  // =========================================================================
  {
    id: "diffie-secret",
    title: "The Strangers' Agreement",
    trackId: "publickey",
    difficulty: "intermediate",
    category: "Key Agreement",
    story: "Alice and Bob agree on public parameters: prime p = 23 and generator g = 5. Alice selects private key a = 6, and Bob sends his public key B = 8.",
    question: "What shared secret s does Alice compute? (Calculate B^a mod p = 8^6 mod 23)",
    intercept: "p = 23, g = 5, a = 6, B = 8",
    hint: "8^2 = 64 ≡ 18 (mod 23) ≡ -5 (mod 23). Square and multiply to find 8^6 mod 23.",
    solution: "12",
    explanation: "8^2 = 64 ≡ 18 (mod 23). 8^4 ≡ 18^2 = 324 ≡ 2 (mod 23). 8^6 = 8^4 × 8^2 ≡ 2 × 18 = 36 ≡ 12 (mod 23). Alice and Bob establish shared secret key 12.",
    toolId: "diffie-hellman",
  },
  {
    id: "dh-small-subgroup",
    title: "Diffie-Hellman Small Subgroup Confinement",
    trackId: "publickey",
    difficulty: "advanced",
    category: "Protocol Exploitation",
    story: "In an unvalidated Diffie-Hellman exchange with p = 23, Mallorie sends an evil public key A' = 22 ≡ -1 (mod 23) to Bob.",
    question: "Bob computes shared secret s = (A')^b mod 23 for his secret b. What are the only two possible values that s can evaluate to?",
    intercept: "A' = -1 (mod 23), s = (-1)^b mod 23",
    hint: "What is (-1)^b when b is even? What is (-1)^b when b is odd?",
    solution: "1,22",
    explanation: "(-1)^b can only take two values: if b is even, (-1)^b = 1; if b is odd, (-1)^b = -1 ≡ 22 (mod 23). The shared keyspace is confined from 22 possibilities down to just 2, allowing an attacker to decrypt traffic instantly.",
    toolId: "diffie-hellman",
  },
  {
    id: "ecdsa-nonce-reuse",
    title: "Sony PS3 Epic Fail: ECDSA Nonce Reuse",
    trackId: "publickey",
    difficulty: "advanced",
    category: "Signature Exploitation",
    story: "In 2010, the PlayStation 3 code signing keys were compromised because Sony's developers used a static, repeated random nonce k across multiple ECDSA signatures.",
    question: "Given two signatures (r, s1) and (r, s2) with identical r on messages with hashes z1 and z2 modulo curve order n, what formula recovers the nonce k?",
    intercept: "s1 = k⁻¹(z1 + r·d) mod n\ns2 = k⁻¹(z2 + r·d) mod n",
    hint: "Subtract s2 from s1: s1 - s2 = k⁻¹(z1 - z2) mod n. Multiply both sides by k and divide by (s1 - s2).",
    solution: "(z1-z2)/(s1-s2)",
    explanation: "s1 - s2 = k⁻¹(z1 - z2) (mod n). Multiplying by k yields k(s1 - s2) ≡ z1 - z2 (mod n), so k = (z1 - z2)·(s1 - s2)⁻¹ mod n. Once k is known, the master private key d is recovered immediately: d = (s1·k - z1)·r⁻¹ mod n.",
    toolId: "ecdsa",
  },

  // =========================================================================
  // 7. HASH FUNCTIONS, INTEGRITY & PRNGs
  // =========================================================================
  {
    id: "hash-length-extension",
    title: "Merkle-Damgård Length Extension Attack",
    trackId: "hashing",
    difficulty: "advanced",
    category: "Hash Architecture Exploit",
    story: "A web API authenticates requests using raw SHA-256: H = SHA256(secret || 'user=guest'). An attacker does NOT know the secret key, but wants to append '&role=admin' to the message.",
    question: "Why can the attacker forge SHA256(secret || 'user=guest' || padding || '&role=admin') without knowing the secret?",
    intercept: "Construction: H(secret || message)",
    hint: "In Merkle-Damgård hashes (MD5, SHA-1, SHA-256), the output hash IS the final internal state vector (h0...h7). Feeding that state into the compression function allows continuing the hash on new data.",
    solution: "INTERNAL STATE",
    explanation: "Because SHA-256 follows the Merkle-Damgård construction without output truncation or a secret-prefix MAC construct (like HMAC), the hash digest directly leaks the compression engine's internal register state. The attacker initializes SHA-256 with that state and continues hashing.",
    toolId: "sha256",
  },
  {
    id: "birthday-collision-math",
    title: "The Birthday Paradox in Hash Collisions",
    trackId: "hashing",
    difficulty: "intermediate",
    category: "Collision Resistance",
    story: "A legacy checksum algorithm outputs a 32-bit hash (2³² = 4,294,967,296 possible hash values).",
    question: "Approximately how many randomly chosen messages must an attacker hash to have a 50% probability of finding a hash collision? (Calculate √2³² = 2¹⁶)",
    intercept: "Bit length: n = 32 bits",
    hint: "By the birthday bound, collision probability reaches ~50% after roughly √(2^n) = 2^(n/2) hashes.",
    solution: "65536",
    explanation: "By the Birthday Problem, the expected number of samples before finding two identical hashes in a space of size N = 2^32 is approximately √(π/2 × 2^32) ≈ 1.25 × 2^16 = 1.25 × 65536 ≈ 82,000, with 2^16 = 65,536 being the fundamental order of magnitude.",
    toolId: "sha256",
  },
  {
    id: "lcg-prng-prediction",
    title: "Cracking the Linear Congruential Generator",
    trackId: "security",
    difficulty: "advanced",
    category: "PRNG Prediction",
    story: "A gambling site generates lottery tokens using a standard Linear Congruential Generator: X_{n+1} = (a · X_n + c) mod m, with modulus m = 256, multiplier a = 5, and increment c = 3. The current seed is X_0 = 10.",
    question: "Compute the next pseudo-random token X_1.",
    intercept: "X_0 = 10, a = 5, c = 3, m = 256",
    hint: "X_1 = (5 × 10 + 3) mod 256. What is 53 mod 256?",
    solution: "53",
    explanation: "X_1 = (5 × 10 + 3) mod 256 = 53 mod 256 = 53. LCGs are completely deterministic and must NEVER be used for cryptographic key generation or session tokens (CWE-338).",
    toolId: "modular-arithmetic",
  },

  // =========================================================================
  // 8. POST-QUANTUM LATTICE CRYPTANALYSIS
  // =========================================================================
  {
    id: "lattice-cvp-rounding",
    title: "Babai's Closest Vector Projection",
    trackId: "postquantum",
    difficulty: "advanced",
    category: "Lattice Cryptography",
    story: "In a 2D lattice spanned by orthogonal basis vectors b1 = (4, 0) and b2 = (0, 4), a noisy ciphertext vector t = (7.8, 4.3) was received.",
    question: "Using Babai's rounding algorithm, what are the integer coefficients (c1, c2) that define the closest lattice point c1·b1 + c2·b2?",
    intercept: "b1 = (4, 0), b2 = (0, 4), target t = (7.8, 4.3)",
    hint: "c1 = round(7.8 / 4) = round(1.95). c2 = round(4.3 / 4) = round(1.075).",
    solution: "2,1",
    explanation: "c1 = ⌊7.8 / 4⌉ = ⌊1.95⌉ = 2. c2 = ⌊4.3 / 4⌉ = ⌊1.075⌉ = 1. The closest lattice point is 2·b1 + 1·b2 = (8, 4). The coefficients are (2, 1).",
    toolId: "attacks",
  },
  {
    id: "kyber-noise-overflow",
    title: "ML-KEM Decryption Failure Threshold",
    trackId: "postquantum",
    difficulty: "advanced",
    category: "Lattice Noise Analysis",
    story: "In NIST FIPS 203 (ML-KEM / Kyber), the modulus is q = 3329. Decryption succeeds if and only if the accumulated noise vector satisfies |e_total| < ⌊q / 4⌋.",
    question: "What is the maximum integer noise bound ⌊3329 / 4⌋ before decryption errors occur?",
    intercept: "q = 3329, bound = ⌊q / 4⌋",
    hint: "Divide 3329 by 4 and take the floor (round down).",
    solution: "832",
    explanation: "3329 / 4 = 832.25. The floor is 832. If noise reaches 833 or higher, the received signal crosses the decision boundary and decodes to the opposite binary bit, resulting in a decryption failure.",
    toolId: "pqc",
  },
  {
    id: "dilithium-rejection-sampling",
    title: "Lyubashevsky's Rejection Paradigm",
    trackId: "postquantum",
    difficulty: "intermediate",
    category: "Post-Quantum Signatures",
    story: "In lattice-based signature scheme ML-DSA (CRYSTALS-Dilithium), the signer computes potential signature vector z = y + c·s. If ||z||_∞ falls within bound β of boundary γ1, the signer aborts and restarts.",
    question: "What security flaw occurs if the signer does NOT abort and outputs z directly?",
    intercept: "Condition: ||z||_∞ ≥ γ1 - β without abort",
    hint: "The distribution of z is shifted by c·s. Without rejection, averaging many signatures reveals the shape and direction of secret key s.",
    solution: "SECRET KEY LEAKAGE",
    explanation: "Without rejection sampling, the probability distribution of signature vector z depends directly on secret key s. An adversary collecting a few thousand signatures can compute statistical averages to recover secret key s completely.",
    toolId: "pqc",
  },

  // =========================================================================
  // 9. FORENSICS, STEGANOGRAPHY & PROTOCOL SECURITY
  // =========================================================================
  {
    id: "lsb-stego-extraction",
    title: "Least Significant Bit (LSB) Extraction",
    trackId: "forensics",
    difficulty: "intermediate",
    category: "Digital Forensics",
    story: "An image analysis scanner extracted 8 consecutive pixel color bytes: 0x48, 0x65, 0x6C, 0x6C, 0x6F, 0x20, 0x21, 0x00. Their least significant bits (bit 0) were isolated.",
    question: "Extract bit 0 of each byte (from first to eighth): 0x48(0), 0x65(1), 0x6C(0), 0x6C(0), 0x6F(1), 0x20(0), 0x21(1), 0x00(0). What 8-bit binary string is formed?",
    intercept: "Bytes: 0x48, 0x65, 0x6C, 0x6C, 0x6F, 0x20, 0x21, 0x00",
    hint: "Look at the lowest bit: 0x48 is even (0), 0x65 is odd (1), 0x6C is even (0), 0x6C is even (0), 0x6F is odd (1), 0x20 is even (0), 0x21 is odd (1), 0x00 is even (0).",
    solution: "01001010",
    explanation: "Extracting bit 0: 0x48 & 1 = 0, 0x65 & 1 = 1, 0x6C & 1 = 0, 0x6C & 1 = 0, 0x6F & 1 = 1, 0x20 & 1 = 0, 0x21 & 1 = 1, 0x00 & 1 = 0. The binary stream is 01001010 (ASCII character 'J').",
    toolId: "forensics",
  },
  {
    id: "png-magic-eof-anomaly",
    title: "Polyglot Steganography: The Appended Archive",
    trackId: "forensics",
    difficulty: "intermediate",
    category: "File Forensics",
    story: "A suspected cyber espionage artifact contains a PNG file. Inspection of the hex stream reveals the official PNG End-of-File marker 'IEND' followed immediately by magic bytes '50 4B 03 04'.",
    question: "What file format begins with magic bytes '50 4B 03 04' (ASCII 'PK')?",
    intercept: "Magic Bytes: 50 4B 03 04",
    hint: "Phil Katz created this widely used compression archive format in 1989. His initials 'PK' appear in every header.",
    solution: "ZIP",
    explanation: "Magic bytes 0x50 0x4B 0x03 0x04 correspond to the PKZip file format signature ('PK\\x03\\x04'). Hiding a ZIP archive past the PNG IEND chunk allows the file to render normally as an image while concealing extracted executables.",
    toolId: "forensics",
  },
  {
    id: "shamir-threshold-recon",
    title: "Recovering the Vault Threshold Key",
    trackId: "security",
    difficulty: "intermediate",
    category: "Threshold Cryptography",
    story: "A 3-of-5 Shamir Secret Sharing scheme protects a cryptocurrency custody vault over GF(257). Three trustees provide their shares: (1, 145), (2, 73), (3, 98).",
    question: "What is the master secret S = f(0)?",
    intercept: "Shares: (1, 145), (2, 73), (3, 98) over GF(257)",
    hint: "Use Lagrange Interpolation: S = ∑ y_i × ℓ_i(0) mod 257. Or launch the Shamir Secret Sharing converter tool.",
    solution: "42",
    explanation: "Evaluating the Lagrange basis polynomials at x=0 over GF(257): ℓ_1(0) = 3, ℓ_2(0) = 254 (≡ -3), ℓ_3(0) = 1. S = (145×3 + 73×254 + 98×1) mod 257 = (435 + 18542 + 98) mod 257 = 19075 mod 257 = 42.",
    toolId: "shamir-secret-sharing",
  },
  {
    id: "tls13-mitm-tamper",
    title: "TLS 1.3 AEAD Integrity Abort",
    trackId: "security",
    difficulty: "intermediate",
    category: "Protocol Security",
    story: "During an active Man-In-The-Middle attack on a TLS 1.3 session encrypted with AES-256-GCM, the interceptor flipped a single bit in the Application Data frame.",
    question: "What cryptographic tag verification error does the client or server AEAD engine throw upon receiving the tampered record?",
    intercept: "Alert code: BAD_RECORD_MAC",
    hint: "In AEAD ciphers (GCM or Poly1305), modifying even 1 bit of ciphertext or associated data causes the authentication tag verification to fail.",
    solution: "BAD_RECORD_MAC",
    explanation: "TLS 1.3 mandates AEAD (Authenticated Encryption with Associated Data). Any ciphertext tampering alters the Galois field polynomial tag computation, immediately triggering a fatal BAD_RECORD_MAC alert and session termination.",
    toolId: "handshake",
  },
  {
    id: "schnorr-zkp-imposter",
    title: "Schnorr Identification Soundness",
    trackId: "security",
    difficulty: "advanced",
    category: "Zero-Knowledge Proofs",
    story: "An imposter does NOT know secret discrete log x in y = g^x mod p, but tries to pass the Schnorr 3-move identification protocol by guessing the verifier's challenge bit e in {0, 1}.",
    question: "What is the mathematical probability that the imposter successfully deceives the verifier across 10 consecutive independent rounds? (Format: 1/1024 or 1/2^10)",
    intercept: "10 rounds, success per round = 1/2",
    hint: "In each round, the imposter has a 1/2 chance of guessing e correctly. For 10 independent rounds: (1/2)^10.",
    solution: "1/1024",
    acceptedSolutions: ["1/1024", "1/2^10", "1/2**10", "0.0009765625"],
    explanation: "Because the Schnorr protocol satisfies soundness with error 1/2 per round, an adversary guessing challenges has probability (1/2)^k of cheating across k rounds. For k = 10, the probability is 1/1024 (~0.098%). At k = 40, it is 1/2^40 (< 10⁻¹²).",
    toolId: "zkp",
  },

  // =========================================================================
  // 10. SIDE-CHANNEL & FAULT INJECTION ATTACKS
  // =========================================================================
  {
    id: "rsa-crt-bellcore-fault",
    title: "Bellcore Laser Fault on RSA-CRT",
    trackId: "asymmetric",
    difficulty: "advanced",
    category: "Side-Channel & Fault Attacks",
    story: "An adversary uses optical laser fault injection on a smartcard during RSA-CRT decryption. Modulus N = 187 (= p × q). The valid signature for message m = 35 is S = 13, but the laser pulse induces a hardware bit flip during the modular reduction mod p, producing a corrupted signature S' = 47 while mod q calculation remains uncorrupted.",
    question: "Calculate gcd(S' - S, N) to isolate the corrupted factor and find prime p.",
    intercept: "N = 187, Valid Signature S = 13, Corrupted S' = 47\nTarget: gcd(S' - S, N)",
    hint: "Compute S' - S = 47 - 13 = 34. Then compute gcd(34, 187) using the Euclidean algorithm or the challenge workbench.",
    solution: "17",
    acceptedSolutions: ["17", "P = 17", "P=17"],
    explanation: "Because S' ≢ S (mod p) due to the fault, but S' ≡ S (mod q) was intact, S' - S is a multiple of q but not of p. Therefore, gcd(S' - S, N) immediately isolates prime factor p = 17 (187 / 17 = 11). This is the famous 1996 Boneh-DeMillo-Lipton Bellcore fault attack.",
    toolId: "rsa",
  },
  {
    id: "timing-attack-strcmp",
    title: "Side-Channel Timing Leak: Non-Constant Comparison",
    trackId: "security",
    difficulty: "intermediate",
    category: "Side-Channel & Timing",
    story: "A secure hardware enclave checks an entered 4-byte hexadecimal authorization PIN byte-by-byte using naive non-constant-time comparison: it returns immediately upon detecting the first mismatched byte. An attacker measures server response time down to nanoseconds.",
    question: "Analyze the timing spike pattern below and reconstruct the 4-byte secret hex token (format: 8 uppercase hex digits, e.g. 4B395A21).",
    intercept: "Latency Profile:\n- Byte 1 probe: 0x4B triggers +22ms delay (all other bytes ~10ms)\n- Byte 2 probe: 0x4B 0x39 triggers +44ms delay (all other bytes ~32ms)\n- Byte 3 probe: 0x4B 0x39 0x5A triggers +66ms delay (all other bytes ~54ms)\n- Byte 4 probe: 0x4B 0x39 0x5A 0x21 triggers HTTP 200 SUCCESS (98ms)",
    hint: "Each correct byte match causes the comparison loop to proceed to the next iteration, adding another 22ms. Combine the 4 matched bytes into a single hex string.",
    solution: "4B395A21",
    acceptedSolutions: ["4B395A21", "0x4B395A21"],
    explanation: "Because the comparison fails early upon the first unequal byte, each consecutive byte guess that yields a jump in latency reveals a correct key byte. The sequence 0x4B, 0x39, 0x5A, 0x21 forms the secret authentication token 4B395A21.",
    toolId: "timing",
  },

  // =========================================================================
  // 11. BLOCKCHAIN, MERKLE TREES & SMART CONTRACT CRYPTOGRAPHY
  // =========================================================================
  {
    id: "ecdsa-high-s-malleability",
    title: "EVM ECDSA High-S Signature Malleability",
    trackId: "security",
    difficulty: "advanced",
    category: "Blockchain Cryptography",
    story: "In an early Ethereum smart contract, transactions were checked against signature replay by storing the signature hash. However, secp256k1 curve points (x, y) and (x, -y) share the exact same affine x-coordinate r. Thus for any valid signature (r, s), the complementary tuple (r, s' = n - s mod n) is also mathematically valid for the same message.",
    question: "Given toy curve order n = 256 and valid signature s = 144, calculate the complementary malleable signature s' in decimal.",
    intercept: "Curve Order n = 256\nValid Signature s = 144 (0x90)\nFormula: s' = (n - s) mod n",
    hint: "Subtract s from n: 256 - 144.",
    solution: "112",
    acceptedSolutions: ["112", "0x70"],
    explanation: "Because s' ≡ -s (mod n), both (r, s) and (r, n - s) evaluate to the same public key recovery point R on the elliptic curve. Computing 256 - 144 = 112 yields a second valid signature that changes the transaction hash without invalidating cryptographic verification. BIP-62 and EIP-2 mandate canonical low-s values (s <= n/2) to prevent malleability.",
    toolId: "ecc",
  },
  {
    id: "merkle-tree-domain-separation",
    title: "Merkle Tree Second Pre-Image Forgery",
    trackId: "security",
    difficulty: "intermediate",
    category: "Cryptographic Hash Trees",
    story: "In a naive Merkle tree implementation, leaf hashes and intermediate parent hashes are both calculated as SHA256(data). An attacker can submit an intermediate node hash (LeftChild || RightChild) as a fake leaf node, creating an identical root hash and forging a proof of inclusion.",
    question: "What 1-byte hex prefix does RFC 6962 mandate prepending to leaf data before hashing to establish cryptographic domain separation against intermediate node hashes (which prepend 0x01)? (Format: 0x00)",
    intercept: "RFC 6962 Section 2.1:\nLeaf Hash = SHA-256(0x?? || leaf_data)\nNode Hash = SHA-256(0x01 || left_child || right_child)",
    hint: "Domain separation uses prefix 0x01 for internal parent nodes and 0x00 for terminal leaf nodes.",
    solution: "0x00",
    acceptedSolutions: ["0x00", "00", "0X00", "ZERO"],
    explanation: "RFC 6962 and Certificate Transparency mandate prepending byte 0x00 to leaf hashes and byte 0x01 to interior node hashes. This prevents second pre-image attacks where an attacker tricks a verifier into accepting an interior branch node hash as an authentic leaf.",
    toolId: "merkle",
  },

  // =========================================================================
  // 12. ADVANCED PUBLIC KEY & DISCRETE LOGARITHM CRYPTANALYSIS
  // =========================================================================
  {
    id: "rsa-common-factor-gcd",
    title: "Shared Modulus Factor: The IoT PRNG Failure",
    trackId: "asymmetric",
    difficulty: "intermediate",
    category: "Public Key Cryptanalysis",
    story: "An internet-wide network telemetry scanner collected millions of RSA public keys from embedded routers. Due to low entropy during system boot, two independent devices generated RSA moduli N1 and N2 that inadvertently share one identical prime factor p.",
    question: "Calculate the greatest common divisor p = gcd(N1, N2) to factor both keys completely.",
    intercept: "N1 = 3233\nN2 = 4453\nTarget: gcd(N1, N2)",
    hint: "Use the Euclidean algorithm or the GCD workbench. Divide 4453 by 3233 to find the remainder.",
    solution: "61",
    acceptedSolutions: ["61", "P = 61", "P=61"],
    explanation: "Running the Euclidean algorithm: gcd(4453, 3233) = 61. Modulus N1 factors as 61 × 53, and N2 factors as 61 × 73. In 2012, Heninger et al. used this exact batch GCD attack across the IPv4 space to instantly crack tens of thousands of real-world TLS and SSH host keys.",
    toolId: "rsa",
  },
  {
    id: "bleichenbacher-e3-forgery",
    title: "Bleichenbacher Low-Exponent RSA Signature Forgery",
    trackId: "asymmetric",
    difficulty: "advanced",
    category: "Public Key Cryptanalysis",
    story: "An unhardened TLS verification engine validates RSA signatures with e = 3. It checks that decrypted signature S³ (mod N) starts with PKCS#1 v1.5 header '00 01 FF ... 00 [ASN.1 DigestInfo] [SHA1]', but fails to check that padding reaches the end of the block, ignoring low-order bytes after the hash. An attacker pads the payload and computes a value without modulus wraparound.",
    question: "Because S³ is smaller than modulus N, what exact standard inverse power operation can the attacker execute directly over the integers to generate the forged signature S without knowing private key d?",
    intercept: "Signature condition: S^3 = Target_Padded_Prefix * 2^k + Garbage < N",
    hint: "Since S³ < N, no modular reduction occurs (S³ mod N = S³). To solve S³ = X over regular integers, take the ...",
    solution: "CUBE ROOT",
    acceptedSolutions: ["CUBE ROOT", "INTEGER CUBE ROOT", "CUBEROOT"],
    explanation: "Because the vulnerable parser allows trailing garbage, the attacker crafts a number X matching the required prefix with garbage bits set to make X a perfect cube over the integers. Calculating the standard integer cube root ∛X yields signature S. When the server cubes S mod N, S³ < N so no reduction happens, and the prefix check succeeds perfectly. This is Bleichenbacher's 2006 attack on PKCS#1 v1.5.",
    toolId: "rsa",
  },
  {
    id: "pohlig-hellman-smooth-dlog",
    title: "Pohlig-Hellman Attack on Smooth Group Orders",
    trackId: "asymmetric",
    difficulty: "advanced",
    category: "Discrete Logarithms",
    story: "A legacy cryptographic library configured Diffie-Hellman using a prime p = 601. An analyst discovers that p - 1 = 600 factors completely into small primes: 2³ × 3 × 5² (it is 5-smooth). Instead of solving discrete logarithm g^x ≡ y (mod p) over the entire group, an attacker projects the equation into small cyclic subgroups of sizes 8, 3, and 25, solving each in milliseconds, and combines the results via Chinese Remainder Theorem.",
    question: "What is the formal name of this famous discrete logarithm algorithm for smooth orders? (Format: Algorithm Name)",
    intercept: "Group: Z_p* with p = 601\np - 1 = 600 = (2^3) * 3 * (5^2)\nSubgroups: Z_8, Z_3, Z_25",
    hint: "Invented by Roland Silver, Stephen Pohlig, and Martin Hellman in 1978.",
    solution: "POHLIG-HELLMAN",
    acceptedSolutions: ["POHLIG-HELLMAN", "POHLIG HELLMAN", "POHLIG-HELLMAN ALGORITHM"],
    explanation: "The Pohlig-Hellman algorithm reduces the discrete logarithm problem in a group of order n to discrete logarithms in subgroups whose orders are prime power factors of n. If all prime factors are small (smooth order), Pohlig-Hellman runs in O(∑ e_i (log n + √p_i)) time instead of exponential time, completely breaking Diffie-Hellman.",
    toolId: "dh",
  },

  // =========================================================================
  // 13. MODERN AUTHENTICATED & SYMMETRIC ENCRYPTION
  // =========================================================================
  {
    id: "gcm-forbidden-attack",
    title: "AES-GCM Forbidden Attack: Reused Nonce Catastrophe",
    trackId: "symmetric",
    difficulty: "advanced",
    category: "Authenticated Encryption",
    story: "An automated backup client encrypted two separate HTTP payloads using AES-GCM with the identical 96-bit Initialization Vector (IV). In Galois/Counter Mode, GHASH calculates authentication tags over GF(2¹²⁸) as: T = (C_1 · H^m + ... + L · H) ⊕ E_K(IV || 1). Because the IV was reused, the one-time OTP mask E_K(IV || 1) is identical for both messages.",
    question: "XORing the two authentication tag equations (T1 ⊕ T2) cancels out the encryption mask. Factoring the resulting polynomial over GF(2¹²⁸) allows the attacker to recover what critical internal secret subkey? (Two words)",
    intercept: "T1 ⊕ T2 = [GHASH(C1) ⊕ GHASH(C2)] * H\nTarget: Internal 128-bit key H",
    hint: "GHASH evaluates a polynomial in H over GF(2^128). The subkey H = AES_K(0^128) is called the ... key.",
    solution: "HASH KEY",
    acceptedSolutions: ["HASH KEY", "GHASH KEY", "H KEY", "AUTHENTICATION KEY"],
    explanation: "In AES-GCM, the internal GHASH subkey H is generated as H = AES_K(0¹²⁸). When a nonce is reused, the OTP mask cancels out upon XORing the tags, yielding a polynomial whose roots include H. Once H is recovered, an attacker can forge valid authentication tags for arbitrary chosen ciphertexts without knowing master key K. This is Antoine Joux's 2006 'Forbidden Attack'.",
    toolId: "aes",
  },
  {
    id: "meet-in-the-middle-2des",
    title: "Double-DES Meet-in-the-Middle Collapse",
    trackId: "symmetric",
    difficulty: "intermediate",
    category: "Block Cipher Cryptanalysis",
    story: "To prevent brute-force attacks on 56-bit DES, an organization encrypted data twice with two independent keys: C = E_K2(E_K1(P)), believing it offered 112 bits of security (2¹¹² operations). Diffie and Hellman showed that given one plaintext-ciphertext pair (P, C), an attacker can compute table T = {E_k(P)} for all 2⁵⁶ keys, and then test D_k(C) against T until a match occurs.",
    question: "What is the effective operation complexity (number of cipher operations) required to break Double DES via Meet-in-the-Middle? (Format: 2^57 or 2^56)",
    intercept: "Architecture: C = E_K2(E_K1(P))\nForward Table: 2^56 encryptions\nReverse Search: 2^56 decryptions\nTotal Operations: 2^56 + 2^56 = 2 * 2^56",
    hint: "2^56 + 2^56 = 2^1 * 2^56 = 2^(56 + 1).",
    solution: "2^57",
    acceptedSolutions: ["2^57", "2**57", "2^56"],
    explanation: "Meet-in-the-middle trades memory for time: computing 2⁵⁶ forward states and at most 2⁵⁶ backward states requires only 2⁵⁶ + 2⁵⁶ = 2⁵⁷ total encryption/decryption operations. This renders Double DES barely stronger than Single DES (2⁵⁶), proving that simple sequential composition does not double security bit length.",
    toolId: "des",
  },
  {
    id: "rc4-fms-keystream-leak",
    title: "Fluhrer-Mantin-Shamir (FMS) WEP Collapse",
    trackId: "classical",
    difficulty: "intermediate",
    category: "Stream Cipher Vulnerabilities",
    story: "In legacy 802.11b WEP Wi-Fi networks, each frame prepended a cleartext 24-bit Initialization Vector (IV) to the 104-bit secret shared key K. In 2001, cryptanalysts showed that when the IV begins with specific values like (B + 3, 255, V), the first byte of RC4 keystream leaks information about secret key byte K[B] with probability ~5% (far higher than random 1/256).",
    question: "What 3-letter acronym denotes this foundational cryptanalytic attack that made Aircrack and WEP cracking possible?",
    intercept: "Attack Paper: 'Weaknesses in the Key Scheduling Algorithm of RC4' (2001)\nAuthors: Scott Fluhrer, Itsik Mantin, Adi Shamir",
    hint: "Take the first letter of each author's surname: Fluhrer, Mantin, Shamir.",
    solution: "FMS",
    acceptedSolutions: ["FMS", "FMS ATTACK"],
    explanation: "The Fluhrer-Mantin-Shamir (FMS) attack exposed severe structural vulnerabilities in the RC4 Key Scheduling Algorithm (KSA). By capturing several thousand broadcast packets containing weak IVs, an attacker computes statistical majorities to recover the complete 104-bit WEP key in less than two minutes.",
    toolId: "rc4",
  },

  // =========================================================================
  // 14. HOMOMORPHIC & ADVANCED NUMBER THEORETIC SYSTEMS
  // =========================================================================
  {
    id: "paillier-homomorphic-tally",
    title: "Paillier Additive Homomorphic Tally",
    trackId: "security",
    difficulty: "intermediate",
    category: "Homomorphic Encryption",
    story: "A cryptographic voting booth encrypts votes using the Paillier cryptosystem with modulus n = 101. Paillier is additively homomorphic: multiplying two ciphertexts c1 and c2 modulo n² yields an encryption of the sum of their plaintexts: D(c1 · c2 mod n²) = (m1 + m2) mod n. Precinct 1 recorded m1 = 45 votes and Precinct 2 recorded m2 = 38 votes.",
    question: "When the central election server multiplies the two ciphertexts modulo n² and decrypts the aggregate product, what integer plaintext sum is obtained?",
    intercept: "Modulus n = 101\nPrecinct 1 Plaintext: m1 = 45\nPrecinct 2 Plaintext: m2 = 38\nFormula: m_sum = (m1 + m2) mod 101",
    hint: "Calculate (45 + 38) mod 101.",
    solution: "83",
    acceptedSolutions: ["83", "SUM = 83"],
    explanation: "Because Paillier encryption satisfies E(m1) · E(m2) ≡ E(m1 + m2 mod n) (mod n²), the election coordinator aggregates votes homomorphically without ever decrypting individual voter ballots. Decrypting the modular product yields 45 + 38 = 83.",
    toolId: "homomorphic",
  },

  // =========================================================================
  // 15. CLASSICAL TRANSPOSITION & GEOMETRIC CIPHERS
  // =========================================================================
  {
    id: "rail-fence-transposition",
    title: "The Zig-Zag Rail Fence",
    trackId: "classical",
    difficulty: "beginner",
    category: "Classical Transposition",
    story: "A physical espionage dead-drop contained an encrypted strip written across 2 horizontal zig-zag rails (depth 2) and concatenated row by row.",
    question: "Reconstruct the 2-rail zig-zag path and decrypt the 12-letter ciphertext into standard uppercase plaintext with spaces.",
    intercept: "Ciphertext: MEMADWETETAN (Depth = 2)",
    hint: "Length is 12 letters, so Rail 1 has 6 letters ('MEMADW') and Rail 2 has 6 letters ('ETETAN'). Interleave them: 1st from Rail 1 (M), 1st from Rail 2 (E), 2nd from Rail 1 (E), 2nd from Rail 2 (T)...",
    solution: "MEET ME AT DAWN",
    acceptedSolutions: ["MEET ME AT DAWN", "MEETMEATDAWN"],
    explanation: "Separating into two rails of 6 letters: Rail 1: M . E . M . A . D . W . and Rail 2: . E . T . E . T . A . N. Interleaving Rail 1 and Rail 2 gives M-E-E-T-M-E-A-T-D-A-W-N = 'MEET ME AT DAWN'.",
    toolId: "transposition",
  },
  {
    id: "columnar-transposition-key",
    title: "Columnar Transposition: Operation Midnight",
    trackId: "classical",
    difficulty: "intermediate",
    category: "Classical Transposition",
    story: "A World War II tactical alert message of 12 letters was written horizontally into 4 columns under keyword 'ZEUS' and read out vertically in alphabetical column order (E, S, U, Z).",
    question: "Reconstruct the 4-column matrix and decipher the 12-letter plaintext (format: uppercase with spaces).",
    intercept: "Ciphertext: TKOATNTAOACN\nKeyword: ZEUS (Alphabetical column order: E=1, S=2, U=3, Z=4)",
    hint: "With 12 letters and 4 columns, each column has 3 letters. Key columns alphabetical: E ('TKO'), S ('ATN'), U ('TAO'), Z ('ACN'). Place these back into the original word ZEUS (Cols: Z, E, U, S) and read across row by row.",
    solution: "ATTACK AT NOON",
    acceptedSolutions: ["ATTACK AT NOON", "ATTACKATNOON"],
    explanation: "Distributing 12 characters into 4 columns gives 3 rows. Col E = T,K,O; Col S = A,T,N; Col U = T,A,O; Col Z = A,C,N. Aligning by word ZEUS: Col 1(Z): [A,C,N], Col 2(E): [T,K,O], Col 3(U): [T,A,O], Col 4(S): [A,T,N]. Reading rows: Row 1: A-T-T-A; Row 2: C-K-A-T; Row 3: N-O-O-N -> 'ATTACK AT NOON'.",
    toolId: "transposition",
  },

  // =========================================================================
  // 16. LATTICES, PROTOCOL RESETS & API AUTHENTICATION
  // =========================================================================
  {
    id: "knapsack-superincreasing-subset",
    title: "Merkle-Hellman Knapsack Subset Sum",
    trackId: "pqc",
    difficulty: "intermediate",
    category: "Lattice Cryptanalysis",
    story: "The Merkle-Hellman additive knapsack was the first general public-key cryptosystem. Private decryption relies on a superincreasing sequence where each element is strictly greater than the sum of all preceding elements: W = [2, 5, 11, 23, 47, 97]. A 6-bit message b = (b1, b2, b3, b4, b5, b6) was encrypted as sum S = ∑ b_i · W_i = 75.",
    question: "Solve the subset sum problem using greedy backwards subtraction to find the 6-bit binary message string (e.g. 010110).",
    intercept: "Superincreasing Sequence W: [2, 5, 11, 23, 47, 97]\nTarget Sum S = 75",
    hint: "Start from the largest element (97): 75 < 97 -> b6 = 0. Next (47): 75 >= 47 -> b5 = 1, remainder = 75 - 47 = 28. Next (23): 28 >= 23 -> b4 = 1, remainder = 28 - 23 = 5. Continue for 11, 5, 2.",
    solution: "010110",
    acceptedSolutions: ["010110", "0, 1, 0, 1, 1, 0", "B = 010110"],
    explanation: "Because sequence W is superincreasing, the subset sum problem is solvable in O(n) greedy steps: 75 < 97 (0); 75 - 47 = 28 (1); 28 - 23 = 5 (1); 5 < 11 (0); 5 - 5 = 0 (1); 0 < 2 (0). Resulting bitvector is 010110 (5 + 23 + 47 = 75). Shamir later broke general Merkle-Hellman using Lenstra-Lenstra-Lovász (LLL) lattice basis reduction.",
    toolId: "pqc",
  },
  {
    id: "krack-wpa2-nonce-reset",
    title: "KRACK: WPA2 4-Way Handshake Nonce Reinstallation",
    trackId: "security",
    difficulty: "intermediate",
    category: "Wireless Protocol Security",
    story: "In 2017, researcher Mathy Vanhoef discovered the KRACK (Key Reinstallation Attack) vulnerability in IEEE 802.11i WPA2. An attacker intercepts and replays Message 3 of the 4-Way Handshake to the client. Upon receiving the retransmitted message, the client reinstalls the already-active Pairwise Transient Key (PTK).",
    question: "Reinstalling the active encryption key causes what critical stream-cipher packet counter to reset back to zero, allowing the attacker to replay frames and decrypt Wi-Fi traffic? (One word)",
    intercept: "WPA2 4-Way Handshake Event:\nStep 1: AP -> Client (Msg 1: ANonce)\nStep 2: Client -> AP (Msg 2: SNonce + MIC)\nStep 3: AP -> Client (Msg 3: Install PTK) <-- Intercepted & Replayed!\nState anomaly: Replay counter / IV resets to 00:00:00:00:00:00",
    hint: "Think about the one-time number or packet counter used with AES-CCMP or TKIP to prevent keystream reuse.",
    solution: "NONCE",
    acceptedSolutions: ["NONCE", "PACKET NUMBER", "REPLAY COUNTER", "IV"],
    explanation: "IEEE 802.11i mandates installing the encryption key upon receipt of Message 3. When reinstalled, state variables including the transmit packet number (nonce/replay counter) reset to 0. When subsequent frames are transmitted with reset counters, the same keystream is reused, enabling immediate plaintext recovery and frame injection.",
    toolId: "handshake",
  },
  {
    id: "jwt-key-confusion-cve",
    title: "JWT HMAC-RSA Algorithmic Key Confusion",
    trackId: "encoding",
    difficulty: "intermediate",
    category: "Web & API Security",
    story: "A web microservice verifies JWT tokens using an asymmetric RSA public key with algorithm RS256. An attacker inspects the server's public endpoint, downloads the public key certificate, changes the JWT header from 'alg':'RS256' to 'alg':'HS256', and signs the token with HMAC-SHA256 using the raw RSA public key PEM string as the secret HMAC key.",
    question: "What is the formal security vulnerability classification for this attack where asymmetric verification keys are processed as symmetric secrets? (Two words: ... Confusion)",
    intercept: "Original Header: {\"alg\":\"RS256\",\"typ\":\"JWT\"}\nForged Header: {\"alg\":\"HS256\",\"typ\":\"JWT\"}\nForged Signature: HMAC-SHA256(header.payload, RSA_PUBLIC_KEY_PEM)",
    hint: "The cryptographic flaw is called either 'Algorithm Confusion' or '... Confusion'.",
    solution: "KEY CONFUSION",
    acceptedSolutions: ["KEY CONFUSION", "ALGORITHM CONFUSION"],
    explanation: "When a library allows user-controlled header algorithms without enforcing expected key types, an attacker switches RS256 (asymmetric) to HS256 (symmetric HMAC). The server then passes its public key to HMAC_Verify(), which treats the public key as the shared HMAC secret, verifying the forged token successfully. This is the notorious CVE-2015-9235 / CVE-2016-5431 Key Confusion flaw.",
    toolId: "jwt",
  },
];
