import type { Lesson } from "./types";

export const classicalLessons: Lesson[] = [
  {
    id: "what-is-cryptography",
    trackId: "classical",
    title: "What cryptography actually promises",
    subtitle: "Confidentiality, integrity, authenticity, non-repudiation",
    formula: {
      expr: "C = Enc_k(P),  P = Dec_k(C),  ∀P ∈ M, ∀k ∈ K",
      badge: "Foundations",
      note: "A cryptosystem is a 5-tuple (M, C, K, Enc, Dec) where M is plaintext space, C is ciphertext space, K is key space, and Dec_k(Enc_k(P)) = P for all valid keys and messages.",
    },
    body: [
      "Cryptography is the mathematical and algorithmic science of securing communication across untrusted, adversary-controlled channels. Rather than being a single tool or magical shield, modern cryptography provides four foundational guarantees that must be individually analyzed and engineered: Confidentiality (preventing unauthorized parties from extracting meaning from the message), Integrity (detecting whether any bit of the message has been altered in transit), Authenticity (verifying the genuine identity of the sender), and Non-repudiation (providing undeniable mathematical proof that the sender generated the message).",
      "Every cryptographic scheme is fundamentally evaluated against a threat model — a formal specification of the adversary's computational bounds, physical access, and attack powers. For example, a cipher might be provably secure against a passive eavesdropper observing ciphertext alone (Ciphertext-Only Attack, or COA), yet completely crumble if an active attacker can trick the system into decrypting chosen ciphertexts (Chosen-Ciphertext Attack, or CCA). Whenever evaluating whether a cryptosystem is 'secure', the only scientifically meaningful question is: 'Secure against whom, under what mathematical assumptions, and with what operational capabilities?'",
      "Kerckhoffs's Principle, articulated by Auguste Kerckhoffs in 1883 in La Cryptographie Militaire, remains the cornerstone of modern security engineering: a cryptosystem should be designed such that it remains completely secure even if everything about the system, except the secret key, is public knowledge. Claude Shannon later restated this as 'the enemy knows the system' (Shannon's Maxim). This principle directly rejects 'security through obscurity' — keeping an algorithm proprietary only creates a fragile illusion of security that evaporates the moment binary code is reverse-engineered, decompiled, or leaked. Today, global standards like AES, SHA-3, and RSA are entirely public, having survived decades of intense cryptanalysis by the world's sharpest researchers.",
    ],
    keyPoints: [
      "Security is meaningless without a formal threat model specifying adversary powers (COA, KPA, CPA, CCA).",
      "Confidentiality does NOT imply integrity: an encrypted message can still be maliciously tampered with unless protected by a MAC or AEAD scheme.",
      "Kerckhoffs's Principle and Shannon's Maxim: Algorithms must be public and peer-reviewed; secrecy resides strictly in the key.",
      "Non-repudiation requires asymmetric digital signatures; symmetric cryptography cannot prevent sender denial.",
    ],
    pitfalls: [
      "Assuming encryption prevents tampering: unauthenticated encryption allows bit-flipping attacks where attackers alter payloads without needing the decryption key.",
      "Relying on secret algorithms ('security through obscurity') instead of peer-reviewed public standards.",
      "Confusing encoding (Base64, hex, URL encoding) with encryption: encodings provide compatibility, not confidentiality.",
      "Neglecting key management: a 256-bit AES key stored in plaintext in client-side code or public GitHub repositories provides zero security.",
    ],
    workedExample: {
      title: "Analyzing CIA Guarantees on a Tampered Message",
      steps: [
        { label: "1. Scenario", detail: "Alice sends encrypted payment instruction 'PAY $100' to Bob using an unauthenticated stream cipher (OTP or CTR mode) with secret key K." },
        { label: "2. Adversary Intercept", detail: "Eve intercepts ciphertext C = P ⊕ K. Even though Eve does not know key K, she knows the plaintext format says 'PAY $100'." },
        { label: "3. Mathematical Bit-Flip", detail: "Eve XORs the ciphertext with mask Δ = ('PAY $100' ⊕ 'PAY $900'). The tampered ciphertext becomes C' = C ⊕ Δ = (P ⊕ K) ⊕ (P ⊕ P') = P' ⊕ K." },
        { label: "4. Bob Decrypts", detail: "Bob computes P' = C' ⊕ K = (P' ⊕ K) ⊕ K = 'PAY $900'. Confidentiality was maintained (Eve never learned K), but Integrity and Authenticity were completely destroyed!" },
      ],
      outcome: "Proves mathematically why confidentiality without cryptographic integrity (MAC or AEAD) is catastrophic.",
    },
    references: [
      {
        title: "Auguste Kerckhoffs: La Cryptographie Militaire (1883)",
        source: "Journal des Sciences Militaires",
        url: "https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle",
        description: "The classic six design requirements for military ciphers that established modern open cryptographic design.",
        type: "spec",
      },
      {
        title: "Claude Shannon: Communication Theory of Secrecy Systems (1949)",
        source: "Bell System Technical Journal",
        url: "https://www.iacr.org/museum/shannon/shannon49.pdf",
        description: "The seminal founding paper of information theory and mathematical cryptography.",
        type: "paper",
      },
      {
        title: "Stanford CS255: Introduction to Cryptography (Dan Boneh)",
        source: "Stanford University",
        url: "https://crypto.stanford.edu/~dabo/cs255/",
        description: "Free, world-class university lecture notes and course material covering rigorous modern cryptographic definitions.",
        type: "tutorial",
      },
    ],
    glossary: [
      { term: "Plaintext", def: "The original intelligible message denoted by P or M." },
      { term: "Ciphertext", def: "The encrypted, unintelligible output message denoted by C." },
      { term: "Key", def: "A secret parameter k chosen from key space K that parameterizes encryption and decryption." },
      { term: "Kerckhoffs's Principle", def: "The design rule stating a cryptosystem must remain secure even if everything except the key is public knowledge." },
      { term: "Shannon's Maxim", def: "'The enemy knows the system' — assume the adversary has full access to the source code, hardware schematics, and protocol specifications." },
      { term: "Threat Model", def: "A formal categorization of the adversary's goals, computational capabilities, and access to inputs/outputs." },
    ],
  },
  {
    id: "caesar",
    trackId: "classical",
    title: "The Caesar cipher",
    subtitle: "One constant shift across the whole alphabet",
    formula: {
      expr: "C(i) = (P(i) + k) mod 26,  P(i) = (C(i) − k) mod 26",
      badge: "mod 26",
      note: "Each plaintext letter is mapped to its numeric alphabet index (A=0, B=1, ..., Z=25), the key shift k is added, and the result is wrapped modulo 26.",
    },
    body: [
      "The Caesar cipher is the quintessential monoalphabetic substitution cipher: every single occurrence of a given plaintext letter is uniformly replaced by a letter located k positions further down the alphabet. Named after Julius Caesar, who used a shift of k = 3 for Roman military communications, it is one of the earliest documented encryption methods in human history.",
      "The fatal flaw of the Caesar cipher is its tiny key space: in a 26-letter alphabet, there are only 25 non-trivial shift keys (a shift of 0 or 26 returns the plaintext unchanged). An adversary intercepting a ciphertext can test all 25 candidate keys in less than a second by computer or in two minutes by hand, immediately recognizing the correct English sentence — a textbook brute-force attack.",
      "Furthermore, monoalphabetic substitution preserves the exact letter frequency distribution of the underlying natural language. In standard English prose, 'E' occurs ~12.7% of the time, followed by 'T' (~9.1%) and 'A' (~8.2%). In any Caesar-encrypted English text of sufficient length, the most frequent ciphertext letter directly reveals the shifted position of 'E'. By computing the Chi-squared goodness-of-fit statistic χ² against expected English frequencies, the true key shift k can be determined deterministically without human intervention.",
    ],
    keyPoints: [
      "Key space |K| = 25 is trivially small and breakable in under 1 millisecond.",
      "Monoalphabetic mapping preserves the global frequency distribution of the source language intact.",
      "Mathematical foundation: Modular addition in the finite cyclic group ℤ/26ℤ.",
      "Vulnerable to both exhaustive key search (brute-force) and frequency analysis.",
    ],
    pitfalls: [
      "Believing a cipher is secure just because humans cannot read the scrambled letters at first glance.",
      "Failing to account for negative numbers when decrypting in programming languages (e.g. `(c - k) % 26` can produce negative results in C, Java, and JavaScript if not written as `((c - k) % 26 + 26) % 26`).",
      "Treating Caesar cipher shifts as encryption in software instead of an educational toy.",
    ],
    workedExample: {
      title: "Encrypting, Decrypting, and Automated Chi-Squared Breaking",
      steps: [
        { label: "1. Letter to Index", detail: "Take plaintext 'ATTACK'. Map characters: A=0, T=19, T=19, A=0, C=2, K=10." },
        { label: "2. Modular Shift (k=3)", detail: "Apply (P + 3) mod 26: (0+3)=3 [D], (19+3)=22 [W], (19+3)=22 [W], (0+3)=3 [D], (2+3)=5 [F], (10+3)=13 [N]." },
        { label: "3. Ciphertext Output", detail: "Ciphertext = 'DWWDFN'." },
        { label: "4. Automated Breaking", detail: "Adversary calculates χ² = Σ (Observed_i - Expected_i)² / Expected_i for all 25 candidate shifts. For shift k=3, χ² reaches an absolute minimum (< 30), identifying 'ATTACK' instantly." },
        { label: "5. Mathematical Decryption", detail: "Apply (C − 3) mod 26: (3−3)=0 [A], (22−3)=19 [T], ..., (13−3)=10 [K] → 'ATTACK'." },
      ],
      outcome: "Resulting ciphertext: 'DWWDFN'. Verified fully reversible and breakable via χ² minimization.",
    },
    references: [
      {
        title: "Suetonius: The Twelve Caesars (Life of Julius Caesar, Section 56)",
        source: "Perseus Digital Library",
        url: "https://en.wikipedia.org/wiki/Caesar_cipher",
        description: "Historical account describing Julius Caesar's shift-by-three cipher dispatches.",
        type: "spec",
      },
      {
        title: "Khan Academy: The Caesar Cipher and Modular Arithmetic",
        source: "Khan Academy",
        url: "https://www.khanacademy.org/computing/computer-science/cryptography/crypt/v/caesar-cipher",
        description: "Free beginner-friendly interactive video and practice exercises explaining modular shifts.",
        type: "tutorial",
      },
      {
        title: "Cryptopals Crypto Challenges: Set 1 Challenge 3",
        source: "Cryptopals",
        url: "https://cryptopals.com/sets/1/challenges/3",
        description: "Hands-on coding exercise breaking single-byte character substitution using character frequency scoring.",
        type: "tutorial",
      },
    ],
    toolId: "caesar",
    glossary: [
      { term: "Monoalphabetic Substitution", def: "A cipher where each symbol in the plaintext alphabet is mapped to exactly one fixed symbol in the ciphertext alphabet throughout the entire message." },
      { term: "Brute-Force Attack", def: "An attack that systematically checks all possible keys in the key space until the correct plaintext is recovered." },
      { term: "Cyclic Group ℤ/26ℤ", def: "The algebraic structure of integers modulo 26 under addition, where values wrap around to 0 upon reaching 26." },
      { term: "Chi-Squared Statistic (χ²)", def: "A statistical metric measuring the divergence between observed letter frequencies in a ciphertext and expected frequencies in a natural language." },
    ],
  },
  {
    id: "atbash-rot13",
    trackId: "classical",
    title: "Atbash and ROT13",
    subtitle: "Keyless substitutions and self-inverse maps",
    formula: {
      expr: "Atbash: C(i) = 25 − P(i)  |  ROT13: C(i) = (P(i) + 13) mod 26",
      badge: "Involutions",
      note: "Both transformations are mathematical involutions: f(f(x)) = x. Encrypting ciphertext with the exact same function immediately recovers plaintext.",
    },
    body: [
      "Atbash is an ancient keyless substitution cipher originally used in Hebrew literature (such as the Book of Jeremiah, where 'Babel' is written as 'Sheshach'). It works by reversing the alphabet: the first letter 'A' maps to the last letter 'Z', 'B' maps to 'Y', and so forth. In algebraic terms over ℤ/26ℤ, it evaluates C(i) = (25 - P(i)). Because it has zero secret parameters, anyone who recognizes the scheme can invert it instantaneously; it provides obfuscation, not cryptographic secrecy.",
      "ROT13 ('Rotate by 13 places') is a modern computing fixture created on Usenet newsgroups in the 1980s. Because the standard Latin alphabet contains 26 letters, shifting by exactly half (13) makes the operation an involution: applying ROT13 twice rotates by 26 positions (13 + 13 ≡ 0 mod 26), returning the original message without writing separate decryption logic.",
      "Both Atbash and ROT13 illuminate the critical distinction between encoding and encryption. Encodings (like Base64, ASCII, hex, or ROT13) are deterministic transformations designed for compatibility or casual concealment. Encryption depends strictly on a private key. Mistaking an encoding for encryption remains one of the most widespread security mistakes in software engineering.",
    ],
    keyPoints: [
      "An algorithm without a secret key is an encoding or obfuscation, never encryption.",
      "An involution is a function that is its own inverse: f(f(x)) = x. Encryption and decryption use the identical routine.",
      "ROT13 is widely used in online forums to obscure spoilers, puzzle hints, and offensive language from casual glance.",
      "Provides zero cryptographic security against any adversary aware of the algorithm.",
    ],
    pitfalls: [
      "Using ROT13, Base64, or Atbash to protect passwords, API tokens, or user data in production.",
      "Assuming obscure encodings deter hackers or automated vulnerability scanners: automated tools recognize and decode ROT13 instantly.",
      "Confusing reversibility with security: just because an algorithm scrambles data reversibly does not make it a cipher.",
    ],
    workedExample: {
      title: "Demonstrating the ROT13 Involution",
      steps: [
        { label: "1. Plaintext Input", detail: "Target word: 'CRYPTO'. Character indices: C=2, R=17, Y=24, P=15, T=19, O=14." },
        { label: "2. First Application", detail: "Apply (P + 13) mod 26: C(2)+13=15 [P], R(17)+13=30%26=4 [E], Y(24)+13=37%26=11 [L], P(15)+13=28%26=2 [C], T(19)+13=32%26=6 [G], O(14)+13=27%26=1 [B] → 'PELCGB'." },
        { label: "3. Second Application", detail: "Run 'PELCGB' through the exact same formula: P(15)+13=28%26=2 [C], E(4)+13=17 [R], L(11)+13=24 [Y], C(2)+13=15 [P], G(6)+13=19 [T], B(1)+13=14 [O] → 'CRYPTO'." },
      ],
      outcome: "ROT13(ROT13('CRYPTO')) = 'CRYPTO'. Encryption and decryption algorithms are identical.",
    },
    references: [
      {
        title: "RFC 1813: Usenet Netiquette and ROT13 Convention",
        source: "IETF RFC",
        url: "https://www.ietf.org/rfc/rfc1813.txt",
        description: "Official Internet standards document documenting the standard use of ROT13 for spoiler masking.",
        type: "standard",
      },
      {
        title: "Wikipedia: Atbash Cipher and Biblical Cryptography",
        source: "Wikipedia",
        url: "https://en.wikipedia.org/wiki/Atbash",
        description: "Comprehensive historical overview of Atbash in ancient Biblical texts.",
        type: "spec",
      },
    ],
    toolId: "atbash",
    glossary: [
      { term: "Involution", def: "A mathematical function that is its own inverse: f(f(x)) = x for all inputs x in its domain." },
      { term: "Keyless Cipher", def: "An algorithm that transforms text without using a secret key parameter. By modern definition, keyless ciphers are encodings, not true cryptosystems." },
      { term: "Obfuscation", def: "The practice of making code or data difficult for humans to understand without providing mathematical security guarantees against automated cryptanalysis." },
    ],
  },
  {
    id: "affine",
    trackId: "classical",
    title: "The affine cipher",
    subtitle: "Multiply and add, modulo 26",
    formula: {
      expr: "C = (a·P + b) mod 26,  P = a⁻¹(C − b) mod 26",
      badge: "gcd(a, 26) = 1",
      note: "The multiplier a must be coprime to 26 (gcd(a, 26) = 1). If a and 26 shared a factor, multiple plaintext letters would collapse onto the same ciphertext letter, rendering decryption impossible.",
    },
    body: [
      "The affine cipher generalizes the Caesar cipher by combining modular multiplication with modular addition. Each plaintext letter P is first multiplied by slope key a and then shifted by intercept key b modulo 26. This is the first place in classical cryptography where algebraic number theory becomes indispensable.",
      "For decryption to be uniquely reversible, the multiplier a must have a modular multiplicative inverse a⁻¹ mod 26 such that (a · a⁻¹) ≡ 1 mod 26. This inverse exists if and only if gcd(a, 26) = 1. The integers coprime to 26 are {1, 3, 5, 7, 9, 11, 15, 17, 19, 21, 23, 25} (Euler's totient φ(26) = φ(2)·φ(13) = 1 · 12 = 12). With 12 valid multipliers and 26 possible shifts, the affine cipher has a key space of 12 × 26 = 312 keys.",
      "Although 312 keys is larger than Caesar's 25, the affine cipher remains strictly monoalphabetic. Because it maps every letter linearly, an attacker who guesses the identity of just two ciphertext letters (a known-plaintext attack on two letters) can set up a system of two linear modular equations and solve for both a and b in seconds using the Extended Euclidean Algorithm.",
    ],
    keyPoints: [
      "Requires gcd(a, 26) = 1; valid multiplier set size is φ(26) = 12.",
      "Total key space: 12 × 26 = 312 keys — vulnerable to instantaneous brute-force search.",
      "Breakable via known-plaintext attack using just two known letter correspondences.",
      "Modular division does not exist: decryption requires computing modular inverse a⁻¹ mod 26.",
    ],
    pitfalls: [
      "Choosing an even multiplier (e.g. a = 4) or a multiple of 13: gcd(a, 26) > 1 causes multiple plaintexts to map to identical ciphertexts (a non-bijective map), making decryption ambiguous.",
      "Forgetting that modular division does not exist: one must multiply by the modular inverse a⁻¹ mod 26 computed via the Extended Euclidean Algorithm.",
      "Assuming a larger key space (312 vs 25) prevents frequency analysis: the frequency profile is merely permuted, not flattened.",
    ],
    workedExample: {
      title: "Encrypting with a = 5, b = 8 and Decrypting via Modular Inverse",
      steps: [
        { label: "1. Check Coprimality", detail: "Check gcd(5, 26). Factors of 26 are 1, 2, 13, 26. Since gcd(5, 26) = 1, a=5 is a valid multiplier." },
        { label: "2. Find Modular Inverse a⁻¹", detail: "Solve (5 · a⁻¹) ≡ 1 mod 26 using Bézout identity: 5 × 21 = 105 = (4 × 26) + 1 ≡ 1 mod 26. Thus a⁻¹ = 21." },
        { label: "3. Encrypt Letter 'E' (P=4)", detail: "C = (5 × 4 + 8) mod 26 = 28 mod 26 = 2 ('C')." },
        { label: "4. Decrypt Letter 'C' (C=2)", detail: "P = 21 × (2 − 8) mod 26 = 21 × (−6) mod 26 = −126 mod 26 = 4 ('E'). Reconstructed successfully!" },
        { label: "5. Known-Plaintext Attack", detail: "If Eve knows 'E' (4) → 'C' (2) and 'T' (19) → 'U' (20): 2 ≡ 4a + b, 20 ≡ 19a + b. Subtract: 18 ≡ 15a mod 26. Since 15⁻¹ mod 26 = 7: a = (18 × 7) mod 26 = 126 mod 26 = 5. Then b = (2 - 4×5) mod 26 = -18 mod 26 = 8. Key recovered!" },
      ],
      outcome: "'E' encrypts to 'C'; decrypting 'C' recovers 'E' using modular inverse 21. Known plaintext breaks keys instantly.",
    },
    references: [
      {
        title: "William Stallings: Cryptography and Network Security (8th Edition)",
        source: "Textbook Standard",
        url: "https://en.wikipedia.org/wiki/Affine_cipher",
        description: "Chapter 2: Classical Encryption Techniques, modular arithmetic, and affine transformations.",
        type: "book",
      },
      {
        title: "Extended Euclidean Algorithm for Modular Inverses (Khan Academy)",
        source: "Khan Academy",
        url: "https://www.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/the-euclidean-algorithm",
        description: "Interactive guide explaining how Euclid's algorithm finds greatest common divisors and Bézout coefficients.",
        type: "tutorial",
      },
    ],
    toolId: "affine",
    glossary: [
      { term: "Coprime", def: "Two integers a and b are coprime (or relatively prime) if their greatest common divisor is 1: gcd(a, b) = 1." },
      { term: "Modular Multiplicative Inverse", def: "An integer x such that (a · x) ≡ 1 mod m, denoted as a⁻¹ mod m." },
      { term: "Euler's Totient Function φ(n)", def: "The count of positive integers up to n that are coprime to n. For modulus 26, φ(26) = 12." },
      { term: "Known-Plaintext Attack (KPA)", def: "An attack model where the adversary has access to both the plaintext and its corresponding ciphertext for one or more messages." },
    ],
  },
  {
    id: "vigenere",
    trackId: "classical",
    title: "The Vigenère cipher",
    subtitle: "A repeating keyword makes the cipher polyalphabetic",
    formula: {
      expr: "Cᵢ = (Pᵢ + K_(i mod L)) mod 26,  Pᵢ = (Cᵢ − K_(i mod L)) mod 26",
      badge: "L = key length",
      note: "Each letter position is encrypted with a distinct Caesar shift determined by the repeating keyword K of length L. The single-letter frequency profile is flattened.",
    },
    body: [
      "Published in 1553 by Giovan Battista Bellaso and later misattributed to Blaise de Vigenère, the Vigenère cipher was hailed for over three centuries as 'le chiffre indéchiffrable' (the unbreakable cipher). By rotating through L distinct Caesar alphabets according to a secret keyword, identical plaintext letters encrypt to different ciphertext letters, successfully defeating naive single-character frequency counts.",
      "In 1863, Prussian army officer Friedrich Kasiski published the breakthrough cryptanalytic method (independently discovered earlier by Charles Babbage). Kasiski realized that when common English words (like 'THE', 'AND', or 'ING') happen to align at distances that are multiples of key length L, they generate identical ciphertext trigrams. By measuring the greatest common divisor (GCD) of distances between repeated sequences, the adversary deduces candidate key lengths L.",
      "Once L is determined, the cryptanalyst partitions the ciphertext into L interleaved cosets (streams). Each stream is purely a monoalphabetic Caesar cipher! Solving L separate frequency analysis problems breaks the entire cipher. In 1922, William Friedman formulated the Index of Coincidence (IoC), enabling automated algorithmic determination of L without manual Kasiski inspection. The Vigenère cipher demonstrates a vital cryptographic lesson: repeating keys leak periodic structure.",
    ],
    keyPoints: [
      "First major polyalphabetic substitution cipher: resists simple single-letter frequency counting.",
      "Kasiski examination identifies key length L by analyzing spacings between repeated ciphertext sequences.",
      "Index of Coincidence (IoC) provides an automated mathematical technique to confirm key length L.",
      "Once L is known, the cipher collapses into L independent Caesar ciphers, solvable in linear time.",
    ],
    pitfalls: [
      "Assuming that because frequency analysis of single letters is flattened, the cipher is cryptographically strong.",
      "Reusing short keywords (e.g., 'KEY' with L=3), which produce massive periodic repetitions easily cracked by hand.",
      "Confusing polyalphabetic substitution with modern stream ciphers: Vigenère keys repeat periodically, whereas stream ciphers use non-repeating cryptographically secure PRNGs.",
    ],
    workedExample: {
      title: "Kasiski Examination Key-Length Recovery",
      steps: [
        { label: "1. Intercept Ciphertext", detail: "Adversary intercepts ciphertext containing repeated trigram 'VHK' at character positions 24, 72, and 120." },
        { label: "2. Calculate Spacings", detail: "Distance 1: 72 − 24 = 48. Distance 2: 120 − 72 = 48. Distance 3: 120 − 24 = 96." },
        { label: "3. Greatest Common Divisor", detail: "gcd(48, 96) = 48. Factors of 48 are {2, 3, 4, 6, 8, 12, 16, 24, 48}. Key length is almost certainly 4, 6, or 8." },
        { label: "4. Index of Coincidence Verification", detail: "Compute average IoC of columns for candidate L=6: IoC = 0.066 (matches English ~0.067). For L=5, IoC = 0.043 (near random ~0.038). L=6 is confirmed!" },
        { label: "5. Slice & Break", detail: "Slice ciphertext into 6 columns. Solve each column as a Caesar cipher using standard English letter frequencies (highest frequency letter maps to 'E')." },
      ],
      outcome: "Key length L is successfully revealed, reducing polyalphabetic cipher to trivial Caesar slices.",
    },
    references: [
      {
        title: "Friedrich Kasiski: Die Geheimschriften und die Dechiffrir-Kunst (1863)",
        source: "Historical Cryptanalysis",
        url: "https://en.wikipedia.org/wiki/Kasiski_examination",
        description: "The historical publication that formally broke the Vigenère cipher by analyzing periodic repetitions.",
        type: "paper",
      },
      {
        title: "William F. Friedman: The Index of Coincidence (1922)",
        source: "Riverbank Laboratories",
        url: "https://en.wikipedia.org/wiki/Index_of_coincidence",
        description: "Foundational statistical technique measuring letter distribution uniformity to break polyalphabetic ciphers.",
        type: "paper",
      },
      {
        title: "Cryptopals Challenge Set 1: Break Repeating-Key XOR",
        source: "Cryptopals",
        url: "https://cryptopals.com/sets/1/challenges/6",
        description: "The modern byte-level equivalent of the Vigenère attack applied to repeating XOR keys.",
        type: "tutorial",
      },
    ],
    toolId: "vigenere",
    glossary: [
      { term: "Polyalphabetic Substitution", def: "A cipher that uses multiple substitution alphabets across the length of a message to obscure letter frequencies." },
      { term: "Kasiski Examination", def: "A cryptanalytic technique that deduces key length by measuring distances between repeated ciphertext sequences." },
      { term: "Index of Coincidence (IoC)", def: "The probability that two randomly selected letters from a text are identical (~0.067 for English, ~0.038 for uniform random)." },
      { term: "Friedman Test", def: "A statistical test that uses the Index of Coincidence to estimate the key length of a polyalphabetic cipher." },
    ],
  },
  {
    id: "autokey",
    trackId: "classical",
    title: "The autokey cipher",
    subtitle: "Using the message itself as key material",
    formula: {
      expr: "K = primer ‖ P,  Cᵢ = (Pᵢ + Kᵢ) mod 26",
      badge: "Vigenère 1586",
      note: "A short secret primer starts the keystream, followed by the plaintext itself. Because the keystream never repeats, Kasiski examination finds no periodic cycles.",
    },
    body: [
      "Recognizing the vulnerability of repeating keywords in polyalphabetic ciphers, Blaise de Vigenère designed the Autokey cipher in 1586. Instead of cycling a short keyword repeatedly, the autokey cipher uses a short secret primer word for the initial letters, and then appends the plaintext message itself to generate the remaining keystream.",
      "Because the keystream is as long as the message and never repeats periodically, Kasiski examination and Index of Coincidence tests find no repeating patterns. This was a monumental conceptual leap toward the concept of stream ciphers: continuous, non-repeating key generation.",
      "However, the autokey cipher is still breakable because the keystream consists of natural language rather than uniform random bits. Cryptanalysts execute a 'probable-word attack' (crib dragging): assuming a common English word (e.g. 'THAT', 'WITH', 'HAVE') appears in the plaintext, subtracting it from the ciphertext yields candidate keystream fragments. If a fragment looks like valid English, it cascades forward and backward, unzipping the entire message.",
    ],
    keyPoints: [
      "Eliminates periodic key repetition by appending the plaintext to the initial primer.",
      "Immune to standard Kasiski examination and Index of Coincidence periodic tests.",
      "Vulnerable to probable-word attacks because natural language plaintext has high statistical redundancy.",
      "Error propagation: A single corrupted ciphertext character causes cascading errors across subsequent plaintexts.",
    ],
    pitfalls: [
      "Assuming that non-repeating key material is equivalent to random key material: English text keystreams possess the same entropy as English plaintext.",
      "A single transmission error in ciphertext propagates and corrupts all subsequent decrypted letters in autokey mode.",
      "Using plaintext autokey instead of modern pseudorandom generators (PRNGs) like ChaCha20 or AES-CTR.",
    ],
    workedExample: {
      title: "Autokey Encryption and Probable-Word Cryptanalysis",
      steps: [
        { label: "1. Keystream Setup", detail: "Plaintext P = 'ATTACKATDAWN' (length 12). Secret primer = 'QUEEN' (length 5)." },
        { label: "2. Keystream Construction", detail: "Append plaintext: K = 'QUEEN' + 'ATTACKATDA' = 'QUEENATTACKA'." },
        { label: "3. Encrypt Character-by-Character", detail: "A(0)+Q(16)=Q, T(19)+U(20)=N(39%26=13), T(19)+E(4)=X(23), A(0)+E(4)=E, C(2)+N(13)=P(15), K(10)+A(0)=K, A(0)+T(19)=T, T(19)+T(19)=V(38%26=12), A(0)+A(0)=A, C(2)+C(2)=E(4)..." },
        { label: "4. Resulting Ciphertext", detail: "C = 'QNXEPKTVTNWN'." },
        { label: "5. Probable-Word Attack", detail: "Adversary guesses probable word 'ATTACK' at index 5. C[5..10] - 'ATTACK' yields candidate key 'QUEENA' (the primer!), confirming the guess and unraveling the whole text." },
      ],
      outcome: "Ciphertext created without periodic loops, but vulnerable to probable-word cascade cryptanalysis.",
    },
    references: [
      {
        title: "Blaise de Vigenère: Traicté des Chiffres ou Secrètes Manières d'Escrire (1586)",
        source: "Historical Archive",
        url: "https://en.wikipedia.org/wiki/Autokey_cipher",
        description: "The original 16th-century treatise introducing the autokey mechanism.",
        type: "spec",
      },
      {
        title: "David Kahn: The Codebreakers (The Comprehensive History)",
        source: "Scribner",
        url: "https://en.wikipedia.org/wiki/The_Codebreakers",
        description: "Definitive historical work documenting the evolution and cryptanalysis of classical ciphers.",
        type: "book",
      },
    ],
    toolId: "autokey",
    glossary: [
      { term: "Autokey", def: "A cipher where the keystream is generated from the message text itself (either plaintext or ciphertext) following an initial secret seed." },
      { term: "Primer", def: "The short initial secret key word used to encrypt the beginning of an autokey message before the text takes over." },
      { term: "Crib Dragging", def: "A cryptanalytic technique where a known or suspected plaintext fragment (a 'crib') is tested across all possible ciphertext offsets." },
      { term: "Error Propagation", def: "The property where an error in transmitting one character causes multiple subsequent characters to decode incorrectly." },
    ],
  },
  {
    id: "playfair",
    trackId: "classical",
    title: "The Playfair cipher",
    subtitle: "Encrypting letter pairs on a 5×5 square",
    formula: {
      expr: "Digraph (P₁, P₂) → (C₁, C₂) via 5×5 Polybius grid rules",
      badge: "Digram Cipher",
      note: "Same row: replace with letters to the right. Same column: replace with letters below. Rectangle: swap opposite horizontal corners. 'I' and 'J' share a cell to fit 25 letters.",
    },
    body: [
      "Invented in 1854 by scientist Charles Wheatstone and promoted by Lord Playfair, the Playfair cipher was the first practical digraph substitution cipher used in tactical military combat. The British military relied on Playfair through the Boer War and World War I due to its speed in the field without mechanical equipment.",
      "Instead of substituting single characters, Playfair groups plaintext into pairs of letters (digraphs) and maps them across a 5×5 matrix constructed from a secret keyword. By operating on pairs, the alphabet size increases from 26 letters to 26 × 25 = 600 possible digraphs. This completely annihilates single-letter frequency analysis.",
      "Nevertheless, digraph frequencies in English are heavily skewed: pairs like 'TH', 'HE', 'IN', 'ER', and 'RE' occur far more frequently than other combinations. Furthermore, Playfair exhibits structural symmetries: if AB encrypts to CD, then BA encrypts to DC. With roughly a few hundred characters of ciphertext, an adversary can match digraph frequency profiles and reconstruct the 5×5 key grid.",
    ],
    keyPoints: [
      "First practical digraph block cipher; alphabet space expands from 26 letters to 600 pairs.",
      "Destroys single-letter frequency spikes, but leaks digraph statistical distributions.",
      "Three geometric substitution rules: same row (shift right), same column (shift down), rectangle (swap corners).",
      "Historical bridge from character-by-character substitution to modern block ciphers.",
    ],
    pitfalls: [
      "Plaintext double letters in a pair (e.g. 'EE') cannot be encrypted directly: a filler character (e.g. 'X') must be inserted ('EX E').",
      "Odd-length messages require appending a null padding letter ('X' or 'Z') at the end.",
      "The 'I/J' ambiguity: recipients must infer from context whether a decoded 'I' represents 'I' or 'J'.",
    ],
    workedExample: {
      title: "Encrypting Digraph 'HE' on a Keyword Grid",
      steps: [
        { label: "1. Construct 5×5 Matrix", detail: "Keyword 'MONARCHY'. Grid: [M O N A R], [C H Y B D], [E F G I K], [L P Q S T], [U V W X Z]." },
        { label: "2. Locate Digraph 'HE'", detail: "H is at row 1, col 1. E is at row 2, col 0. They form opposite corners of a rectangle." },
        { label: "3. Apply Rectangle Rule", detail: "Pick horizontal corners in the same row: H(r1,c1) becomes C(r1,c0). E(r2,c0) becomes F(r2,c1)." },
        { label: "4. Column Rule Example", detail: "Digraph 'CV': C is (r1,c0), V is (r4,c0) (same column). Shift down: C becomes E(r2,c0), V becomes M(r0,c0) (wraps around). Result: 'EM'." },
        { label: "5. Ciphertext Output", detail: "Digraph 'HE' encrypts to 'CF'." },
      ],
      outcome: "Plaintext pair 'HE' transforms to ciphertext pair 'CF'. Verified reversible by applying inverse rules.",
    },
    references: [
      {
        title: "Charles Wheatstone & Lyon Playfair: The Playfair Cipher (1854)",
        source: "Royal Society Archives",
        url: "https://en.wikipedia.org/wiki/Playfair_cipher",
        description: "Historical documentation of the first practical digraph cipher adopted by the British War Office.",
        type: "paper",
      },
      {
        title: "Helen Fouché Gaines: Cryptanalysis (A Study of Ciphers and Their Solution)",
        source: "Dover Publications",
        url: "https://en.wikipedia.org/wiki/Cryptanalysis_(book)",
        description: "Comprehensive manual on manual cryptanalysis techniques for Playfair, Four-Square, and Bifid ciphers.",
        type: "book",
      },
    ],
    toolId: "playfair",
    glossary: [
      { term: "Digraph", def: "A pair of two consecutive letters (e.g. 'TH', 'HE', 'IN') treated as a single cryptographic unit." },
      { term: "Polybius Square", def: "A 5×5 grid of letters used to translate letters into coordinates or perform geometric substitutions." },
      { term: "Rectangle Rule", def: "The Playfair substitution rule where letters on opposite corners of a rectangle are swapped with the letters in the same row on the opposite corner." },
      { term: "Digraphic Frequency", def: "The statistical probability distribution of two-letter sequences in a given natural language." },
    ],
  },
  {
    id: "transposition",
    trackId: "classical",
    title: "Transposition ciphers",
    subtitle: "Keep the letters, rearrange the order",
    formula: {
      expr: "C = π(P),  where π ∈ S_n is a key-defined permutation of indices",
      badge: "Diffusion",
      note: "Substitution replaces characters while keeping positions fixed. Transposition keeps characters identical while shuffling their positions (diffusion).",
    },
    body: [
      "While substitution ciphers replace symbols with other symbols, transposition ciphers rearrange the order of the symbols without changing their identities. In columnar transposition, the plaintext is written horizontally into rows of fixed width determined by a keyword, and then read out vertically by columns ordered alphabetically by the keyword letters.",
      "A transposition ciphertext exhibits a telltale fingerprint: its single-letter frequency distribution is identical to natural English text (e.g., high counts of E, T, A, O, I, N), yet reading it produces complete gibberish. This signature immediately informs the cryptanalyst that the encryption is a permutation rather than a substitution.",
      "Neither substitution nor transposition alone provides strong security. However, in his landmark 1949 paper, Claude Shannon demonstrated that alternating substitution (confusion) and transposition (diffusion) in successive rounds creates an immensely strong cipher. This exact principle — the Substitution-Permutation Network (SPN) — forms the architectural core of modern ciphers like AES.",
    ],
    keyPoints: [
      "Transposition rearranges positions while preserving letter identities and frequencies intact.",
      "Identified instantly by natural language letter frequencies paired with zero readable words.",
      "Claude Shannon's dual pillars: Substitution provides Confusion; Transposition provides Diffusion.",
      "Breakable via anagramming, bigram scoring (matching 'TH', 'QU', 'IN'), and vowel-consonant clustering.",
    ],
    pitfalls: [
      "Using transposition without substitution: an attacker can reconstruct the grid via anagramming and bigram likelihood scoring.",
      "Short key lengths allow automated brute-force permutation of column orders (e.g. 5! = 120 orders).",
      "Assuming transposition hides message length: transposition ciphers leak exact message length unless padded to fixed block sizes.",
    ],
    workedExample: {
      title: "Columnar Transposition with Key 'ZEBRA'",
      steps: [
        { label: "1. Keyword Alphabetical Order", detail: "Key = 'Z E B R A'. Alphabetical ranking: A=1, B=2, E=3, R=4, Z=5. Column order: (5, 3, 2, 4, 1)." },
        { label: "2. Write Plaintext in Rows", detail: "Plaintext: 'ATTACKATDAWN'. Width = 5. Row 1: A T T A C. Row 2: K A T D A. Row 3: W N X X X (padded to multiple of 5)." },
        { label: "3. Read Columns in Numerical Order", detail: "Col 1 (A): C A X. Col 2 (B): T T X. Col 3 (E): T A N. Col 4 (R): A D X. Col 5 (Z): A K W." },
        { label: "4. Assemble Ciphertext", detail: "C = 'CAXTTXTANADXAKW'." },
        { label: "5. Decryption Reversal", detail: "Recipient computes column length (15 / 5 = 3 rows), writes ciphertext into columns in key order (A, B, E, R, Z), and reads off rows to recover 'ATTACKATDAWN'." },
      ],
      outcome: "Message successfully permuted according to key column order. Preserves unigram frequency profile.",
    },
    references: [
      {
        title: "Claude Shannon: Communication Theory of Secrecy Systems (1949)",
        source: "Bell Labs",
        url: "https://www.iacr.org/museum/shannon/shannon49.pdf",
        description: "Introduces the concepts of Confusion and Diffusion as the dual pillars of modern cryptography.",
        type: "paper",
      },
      {
        title: "William Stallings: Cryptography and Network Security (8th Edition)",
        source: "Pearson",
        url: "https://en.wikipedia.org/wiki/Transposition_cipher",
        description: "Detailed coverage of rail fence, route ciphers, and single/double columnar transposition.",
        type: "book",
      },
    ],
    toolId: "columnar",
    glossary: [
      { term: "Transposition Cipher", def: "An encryption method where characters are shifted to different positions according to a regular system, preserving character identities." },
      { term: "Diffusion", def: "A cryptographic property where changing a single plaintext bit alters many ciphertext bits across the block, dispersing statistical redundancy." },
      { term: "Confusion", def: "A cryptographic property that makes the relationship between the key and the ciphertext as complex and non-linear as possible." },
      { term: "Substitution-Permutation Network (SPN)", def: "A cipher architecture that interleaves non-linear substitution layers (S-boxes) with linear permutation layers (P-boxes)." },
    ],
  },
  {
    id: "frequency-analysis",
    trackId: "classical",
    title: "Breaking ciphers with frequency analysis",
    subtitle: "The first true cryptanalysis, from 9th-century Baghdad",
    formula: {
      expr: "IC = Σ [nᵢ · (nᵢ − 1)] / [N · (N − 1)],   χ² = Σ (Oᵢ − Eᵢ)² / Eᵢ",
      badge: "Al-Kindi c. 850 CE",
      note: "Index of Coincidence (IC) calculates the probability that two randomly selected characters are identical (~0.067 for English, ~0.0385 for uniform random). Chi-squared (χ²) measures statistical fit to known language frequencies.",
    },
    body: [
      "In the 9th century CE in Baghdad during the Islamic Golden Age, polymath Abu Yusuf Ya'qub ibn Ishaq al-Kindi authored 'A Manuscript on Deciphering Cryptographic Messages', establishing the birth of scientific cryptanalysis. Al-Kindi realized that in any natural language, characters do not appear with equal probability. By tabulating the frequency of letters in a ciphertext and aligning them with known language statistics, simple substitutions are systematically broken.",
      "Monoalphabetic ciphers with key spaces as immense as 26! ≈ 4.03 × 10²⁶ (which would take centuries to brute force) fall within minutes to frequency analysis. This illustrates the fundamental cryptographic maxim: key space size is a necessary condition for security, but never a sufficient one. Structural statistical vulnerabilities bypass brute force entirely.",
      "In 1922, William F. Friedman introduced the Index of Coincidence (IoC), providing a rigorous statistical measure of text roughness. Because the IoC remains invariant under monoalphabetic substitution, an analyst can immediately determine whether an unknown ciphertext is monoalphabetic (IC ≈ 0.067) or polyalphabetic/randomized (IC ≈ 0.038), and directly calculate the key length of a Vigenère cipher.",
    ],
    keyPoints: [
      "Al-Kindi (c. 850 CE) invented frequency analysis, breaking monoalphabetic substitution ciphers.",
      "A massive key space (26! ≈ 4.03 × 10²⁶) is completely powerless against statistical distribution attacks.",
      "Index of Coincidence distinguishes monoalphabetic ciphers from polyalphabetic and random ciphers.",
      "N-gram frequency analysis (bigrams like 'TH', trigrams like 'THE') breaks polyalphabetic and transposition ciphers.",
    ],
    pitfalls: [
      "Attempting frequency analysis on very short messages (< 50 characters) where statistical variance causes random fluctuations.",
      "Assuming non-English languages share the 'ETAOIN SHRDLU' distribution (e.g. Spanish most frequent letter is E, followed by A and O; German top letters are E, N, I, S, R).",
      "Relying solely on single-letter counts when analyzing transposition or polygraphic ciphers.",
    ],
    workedExample: {
      title: "Calculating Index of Coincidence on a Sample Text",
      steps: [
        { label: "1. Count Letter Frequencies", detail: "Sample text of N=100 characters. Count frequencies n_A, n_B, ..., n_Z." },
        { label: "2. Compute Pair Combinations", detail: "Sum n_i * (n_i - 1) for each letter from A to Z (number of pairs of identical letters)." },
        { label: "3. Divide by Total Pairs N(N-1)", detail: "Divide the sum by 100 * 99 = 9900." },
        { label: "4. Interpret Result", detail: "If IC ≈ 0.065, the text is monoalphabetic English. If IC ≈ 0.039, the text is polyalphabetic or pseudo-random." },
        { label: "5. Estimate Vigenère Key Length", detail: "Friedman formula: L ≈ (0.027 · N) / [(N - 1)·IC - 0.038·N + 0.065]. For IC=0.045, N=500, L ≈ 5." },
      ],
      outcome: "Quantifies the exact degree of statistical roughness in a message, automating key length deduction.",
    },
    references: [
      {
        title: "Al-Kindi: A Manuscript on Deciphering Cryptographic Messages (c. 850 CE)",
        source: "Historical Archive",
        url: "https://en.wikipedia.org/wiki/Al-Kindi#Cryptography",
        description: "The founding text of cryptanalysis and statistical frequency evaluation.",
        type: "paper",
      },
      {
        title: "Simon Singh: The Code Book (The Story of Secrecy)",
        source: "Public Resource",
        url: "https://en.wikipedia.org/wiki/The_Code_Book",
        description: "Acclaimed history of cryptanalysis from ancient frequency analysis to quantum cryptography.",
        type: "book",
      },
      {
        title: "William F. Friedman: The Index of Coincidence and Its Applications (1922)",
        source: "Riverbank Publications No. 22",
        url: "https://en.wikipedia.org/wiki/Index_of_coincidence",
        description: "The seminal mathematical work establishing coincidence counting in cryptanalysis.",
        type: "paper",
      },
    ],
    toolId: "frequency",
    glossary: [
      { term: "Frequency Analysis", def: "The study of the frequency of letters or groups of letters in a ciphertext to reveal plaintext patterns." },
      { term: "Index of Coincidence (IoC)", def: "A statistical measure of how likely two randomly chosen letters from a text are to be identical." },
      { term: "Chi-Square Test (χ²)", def: "A statistical test used to compare observed character distributions in ciphertext against expected language distributions." },
      { term: "N-gram", def: "A contiguous sequence of n items (unigram = 1 letter, bigram = 2 letters, trigram = 3 letters)." },
    ],
  },
  {
    id: "one-time-pad",
    trackId: "classical",
    title: "The one-time pad",
    subtitle: "The only cipher with a proof of perfect secrecy",
    formula: {
      expr: "C = P ⊕ K,  where |K| = |P|, K ~ Uniform(K), used strictly once",
      badge: "Shannon 1949",
      note: "Perfect Secrecy: P(M = m | C = c) = P(M = m). Observing the ciphertext provides zero information about the plaintext.",
    },
    body: [
      "Invented by Gilbert Vernam in 1917 and mathematically proven by Claude Shannon in 1949, the One-Time Pad (OTP) is the only encryption scheme mathematically proven to be unbreakable. Shannon proved that if the key K is truly random (drawn uniformly from high-entropy physical sources), exactly as long as the plaintext, kept strictly secret, and used exactly once, the ciphertext achieves Information-Theoretic Secrecy (Perfect Secrecy).",
      "Perfect secrecy means that an adversary with infinite computational power and infinite time can learn nothing about the plaintext from the ciphertext. For any given ciphertext C, every possible plaintext of length |C| is generated by some valid key with equal probability. If an attacker intercepts an encrypted 5-letter word, 'HELLO', 'LATER', 'ATTAC', and 'PEACE' are all equally probable decryptions.",
      "The fatal practical limitation is key distribution and reuse. Truly random keys are difficult to generate at scale, distributing keys as large as all transmitted data is logistically impossible for the internet, and key reuse is catastrophic: if C₁ = P₁ ⊕ K and C₂ = P₂ ⊕ K, then C₁ ⊕ C₂ = P₁ ⊕ P₂. The key cancels out completely, exposing the combined plaintexts to simple frequency separation! This exact vulnerability was exploited by the Allied VENONA project to decrypt thousands of Soviet KGB diplomatic cables.",
    ],
    keyPoints: [
      "Proven information-theoretic security: unbreakable even by an adversary with infinite computational power.",
      "Requires three strict conditions: truly random key, |K| ≥ |P|, and absolute zero key reuse.",
      "Reusing a key ('Two-Time Pad') completely cancels the key: C₁ ⊕ C₂ = P₁ ⊕ P₂.",
      "Provides zero integrity: an attacker can flip arbitrary bits in the ciphertext and predictably alter plaintext without detection.",
    ],
    pitfalls: [
      "Using a pseudo-random number generator (PRNG like `Math.random()`) instead of a true hardware random number generator.",
      "Reusing a one-time pad key across multiple messages, which enabled the historical VENONA decrypts.",
      "Assuming OTP provides authentication: an adversary can flip ciphertext bits to tamper with plaintexts without detection.",
      "Logistical impossibility: Distributing gigabytes of random keys securely defeats the purpose of network encryption.",
    ],
    workedExample: {
      title: "The Two-Time Pad Catastrophe (Key Cancellation)",
      steps: [
        { label: "1. Message 1 & 2 Setup", detail: "P₁ = 'YES' [0x59, 0x45, 0x53], P₂ = 'NO ' [0x4E, 0x4F, 0x20]. Secret Key K = [0xA1, 0xB2, 0xC3]." },
        { label: "2. Encryption", detail: "C₁ = P₁ ⊕ K = [0xF8, 0xF7, 0x90]. C₂ = P₂ ⊕ K = [0xEF, 0xFD, 0xE3]." },
        { label: "3. Adversary Intercept & XOR", detail: "Eve XORs both ciphertexts: C₁ ⊕ C₂ = (P₁ ⊕ K) ⊕ (P₂ ⊕ K) = P₁ ⊕ P₂." },
        { label: "4. Resulting Plaintext Stream", detail: "C₁ ⊕ C₂ = [0xF8⊕0xEF, 0xF7⊕0xFD, 0x90⊕0xE3] = [0x17, 0x0A, 0x73] = P₁ ⊕ P₂. The secret key K is 100% eliminated!" },
        { label: "5. Crib Dragging Recovery", detail: "Eve guesses P₁ starts with 'Y' (0x59): 0x17 ⊕ 0x59 = 0x4E ('N'), revealing P₂ starts with 'N'. Both messages unravel simultaneously." },
      ],
      outcome: "Key cancels out completely. Natural language heuristics instantly recover both P₁ and P₂.",
    },
    references: [
      {
        title: "Claude Shannon: Communication Theory of Secrecy Systems (1949)",
        source: "Bell System Technical Journal",
        url: "https://www.iacr.org/museum/shannon/shannon49.pdf",
        description: "The mathematical proof that the one-time pad achieves perfect secrecy and that |K| >= |M| is required.",
        type: "paper",
      },
      {
        title: "NSA VENONA Historical Declassified Archive",
        source: "National Security Agency (NSA)",
        url: "https://www.nsa.gov/Helpful-Links/NSA-FOIA/Declassification-Transparency-Initiatives/Historical-Releases/Venona/",
        description: "Declassified reports showing how Soviet one-time pad reuse allowed US/UK cryptanalysts to decrypt thousands of KGB messages.",
        type: "spec",
      },
      {
        title: "Cryptopals Challenge Set 1: Single-Byte XOR & Repeating-Key XOR",
        source: "Cryptopals",
        url: "https://cryptopals.com/sets/1/challenges/3",
        description: "Practical exercises demonstrating why stream ciphers fail when keystreams repeat.",
        type: "tutorial",
      },
    ],
    toolId: "otp",
    glossary: [
      { term: "Perfect Secrecy", def: "A state where the ciphertext gives an eavesdropper zero information about the plaintext beyond its maximum length: P(M=m | C=c) = P(M=m)." },
      { term: "Information-Theoretic Security", def: "Security that cannot be broken even by an attacker with infinite computing power, because the ciphertext is mathematically independent of the plaintext." },
      { term: "Two-Time Pad Attack", def: "A cryptanalytic attack where two ciphertexts encrypted with the same keystream are XORed together, cancelling out the key and exposing P₁ ⊕ P₂." },
      { term: "Vernam Cipher", def: "The polyalphabetic stream cipher patented by Gilbert Vernam in 1917 using XOR logic on teleprinter tape." },
    ],
  },
  {
    id: "hill-cipher",
    trackId: "classical",
    title: "The Hill cipher",
    subtitle: "Polygraphic substitution with matrix linear algebra",
    formula: {
      expr: "C = K · P mod 26,  P = K⁻¹ · C mod 26",
      badge: "Lester Hill 1929",
      note: "Plaintext is partitioned into n-dimensional vectors and multiplied by an n×n key matrix K modulo 26. K is invertible if and only if gcd(det(K), 26) = 1.",
    },
    body: [
      "Invented by American mathematician Lester S. Hill in 1929, the Hill cipher was the first polygraphic cipher to harness matrix linear algebra over the modular ring ℤ/26ℤ. By grouping letters into n-dimensional vectors and multiplying them by an n×n invertible key matrix, the Hill cipher mixes character values across the entire vector block.",
      "This simultaneous mixing produces diffusion: changing a single plaintext character alters all n characters in the resulting ciphertext block. Frequency analysis on individual letters is completely disabled because identical letters encrypt to entirely different letters depending on the neighbors they are paired with.",
      "The fatal weakness of the Hill cipher is that matrix multiplication is purely linear. Because there are no non-linear operations (no S-boxes), the cipher falls trivially to a Known-Plaintext Attack (KPA). An adversary who obtains just n plaintext-ciphertext vector pairs can formulate the matrix equation C = K · P mod 26 and solve for the entire key matrix K = C · P⁻¹ mod 26 via Gaussian elimination in milliseconds.",
    ],
    keyPoints: [
      "First cipher to apply linear algebra, matrix determinants, and modular inverses.",
      "Key matrix K requires gcd(det(K), 26) = 1 to ensure a valid inverse matrix K⁻¹ exists.",
      "Produces linear block diffusion across n-character vectors.",
      "Vulnerable to Known-Plaintext Attacks because pure linearity offers zero cryptographic confusion.",
    ],
    pitfalls: [
      "Choosing a key matrix whose determinant shares factors with 26 (i.e. det(K) is even or divisible by 13): the matrix has no inverse and messages cannot be decrypted.",
      "Using linear transformations alone in modern systems: modern ciphers (like AES) require non-linear S-boxes to resist linear cryptanalysis.",
      "Padding errors: If plaintext length is not a multiple of block size n, dummy characters must be added.",
    ],
    workedExample: {
      title: "Encrypting with a 2×2 Hill Matrix and Solving for Inverse",
      steps: [
        { label: "1. Key Matrix Setup", detail: "K = [[3, 3], [2, 5]]. Compute det(K) = (3×5 − 3×2) = 15 − 6 = 9. Check gcd(9, 26) = 1. Invertible!" },
        { label: "2. Invert Determinant", detail: "Solve (9 · d⁻¹) ≡ 1 mod 26. 9 × 3 = 27 ≡ 1 mod 26. Thus det(K)⁻¹ = 3." },
        { label: "3. Adjugate Matrix", detail: "adj(K) = [[5, -3], [-2, 3]] mod 26 = [[5, 23], [24, 3]]. K⁻¹ = 3 · adj(K) = [[15, 69%26=17], [72%26=20, 9]]." },
        { label: "4. Plaintext Vector", detail: "Encrypt 'HI'. H=7, I=8. Vector P = [7, 8]ᵀ." },
        { label: "5. Matrix Multiplication", detail: "Row 1: (3×7 + 3×8) = 21 + 24 = 45 ≡ 19 ('T'). Row 2: (2×7 + 5×8) = 14 + 40 = 54 ≡ 2 ('C'). Ciphertext = 'TC'." },
        { label: "6. Decryption Verification", detail: "P = K⁻¹ · [19, 2]ᵀ: Row 1 = (15×19 + 17×2) = 285 + 34 = 319 ≡ 7 ('H'). Row 2 = (20×19 + 9×2) = 380 + 18 = 398 ≡ 8 ('I')." },
      ],
      outcome: "Plaintext 'HI' transforms into ciphertext 'TC' and decrypts back to 'HI' flawlessly.",
    },
    references: [
      {
        title: "Lester S. Hill: Cryptography in an Algebraic Alphabet (1929)",
        source: "The American Mathematical Monthly",
        url: "https://en.wikipedia.org/wiki/Hill_cipher",
        description: "The original paper introducing linear algebra and matrix arithmetic to cryptographic systems.",
        type: "paper",
      },
      {
        title: "William Stallings: Cryptography and Network Security (8th Edition)",
        source: "Pearson",
        url: "https://en.wikipedia.org/wiki/Hill_cipher",
        description: "Chapter 2: Linear algebra in cryptography and known-plaintext attacks against Hill matrices.",
        type: "book",
      },
    ],
    toolId: "hill-cipher",
    glossary: [
      { term: "Hill Cipher", def: "A polygraphic substitution cipher based on linear algebra, where blocks of plaintext letters are multiplied by an invertible key matrix modulo 26." },
      { term: "Adjugate Matrix", def: "The transpose of the cofactor matrix of a square matrix, used in Cramer's rule to calculate matrix inverses." },
      { term: "Modular Determinant", def: "The scalar determinant of a matrix evaluated under modular arithmetic." },
      { term: "Known-Plaintext Matrix Attack", def: "Solving for the key matrix K by inverting the plaintext matrix: K = C · P⁻¹ mod 26." },
    ],
  },
  {
    id: "enigma",
    trackId: "classical",
    title: "The Enigma machine",
    subtitle: "Electro-mechanical rotors, Steckerbrett and the dawn of computing",
    formula: {
      expr: "E = P · R_R · R_M · R_L · U · R_L⁻¹ · R_M⁻¹ · R_R⁻¹ · P",
      badge: "Bletchley Park",
      note: "Electrical current travels through the plugboard (P), three wired rotors (right, middle, left), hits the reflector (U), and returns in reverse. Rotors step with each keypress.",
    },
    body: [
      "Used by the German military throughout World War II, the Enigma machine was an electro-mechanical rotor cipher that produced dynamic polyalphabetic substitution. With each keystroke, mechanical pawls stepped the rightmost rotor; after 26 steps, a turnover notch stepped the middle rotor, which eventually stepped the left rotor like an odometer. Combined with a plugboard (Steckerbrett) swapping 10 pairs of letters, Enigma offered a staggering key space exceeding 1.58 × 10²⁰ possible configurations.",
      "In 1932, young Polish mathematician Marian Rejewski achieved one of history's greatest cryptanalytic triumphs: using permutation group theory, cycle notation, and French intelligence cribs, he solved the internal wirings of the German military Enigma rotors without ever having seen the physical machine.",
      "At Bletchley Park, Alan Turing, Gordon Welchman, and their team constructed the electro-mechanical 'Bombe' machines to deduce daily rotor settings at industrial speed. The cryptanalysts exploited a critical architectural flaw: the Reflector (Umkehrwalze). Because current entered through one contact and reflected out another, no letter could ever encrypt as itself (E(x) ≠ x). Cryptanalysts used this negative certainty to test 'cribs' (guessed words like 'WETTERVORHERSAGE' — weather forecast) and eliminate millions of rotor alignments instantly through closed electrical loop contradictions.",
    ],
    keyPoints: [
      "Dynamic polyalphabetic machine cipher with 3 to 4 stepping rotors and plugboard permutation.",
      "First broken by Polish cryptanalysts using permutation cycle theory, then mechanized by Turing's Bombe.",
      "Fatal architectural flaw: A letter can NEVER encrypt to itself (E(x) ≠ x).",
      "Human operational failures (predictable call signs, repeated message keys) were crucial to breaking the cipher.",
    ],
    pitfalls: [
      "Believing a massive key space (1.58 × 10²⁰) guarantees security when architectural flaws (reflector property) provide shortcuts.",
      "Human procedural laziness: German radio operators repeatedly used predictable message keys, repetitive call signs, and identical daily weather headers.",
      "Double-stepping anomaly: Enigma's middle rotor steps twice when engaged by the left rotor pawl, an idiosyncrasy that must be accounted for in emulation software.",
    ],
    workedExample: {
      title: "Exploiting the Reflector Flaw E(x) ≠ x via Crib Alignment",
      steps: [
        { label: "1. Crib Guess", detail: "Cryptanalyst guesses that message starts with 'WETTER' (German for 'weather')." },
        { label: "2. Ciphertext Intercept", detail: "Ciphertext at offset 0: 'Q W B M X L'." },
        { label: "3. Check Position-by-Position Collisions", detail: "Compare index 0: 'W' vs 'Q' (valid). Index 1: 'E' vs 'W' (valid). Index 2: 'T' vs 'B' (valid). Index 3: 'T' vs 'M' (valid). Index 4: 'E' vs 'X' (valid). Index 5: 'R' vs 'L' (valid)." },
        { label: "4. Collision Detected at Offset 1!", detail: "Suppose at offset 1 ciphertext was 'E'. Since plaintext letter 1 is 'E', and Enigma can NEVER encrypt 'E' to 'E', this crib alignment is 100% ruled out instantly!" },
        { label: "5. Turing's Bombe Loop Deduction", detail: "Once an alignment has no collisions, closed loops in the crib graph (e.g. A → B → C → A) are wired into the Bombe. If voltage reaches all test wires, the trial rotor setting is logically impossible and discarded." },
      ],
      outcome: "The Reflector flaw allowed Turing's Bombe to reject millions of false rotor positions without full decryption.",
    },
    references: [
      {
        title: "Alan Turing: Treatise on the Enigma ('The Prof's Book', 1940)",
        source: "The National Archives (UK)",
        url: "https://en.wikipedia.org/wiki/Cryptanalysis_of_the_Enigma",
        description: "Alan Turing's declassified masterwork detailing the mathematical methods used at Bletchley Park to break the naval Enigma.",
        type: "paper",
      },
      {
        title: "Marian Rejewski: How Polish Mathematicians Deciphered the Enigma (1980)",
        source: "IEEE Annals of the History of Computing",
        url: "https://en.wikipedia.org/wiki/Marian_Rejewski",
        description: "Rejewski's first-hand historical account detailing the theorem of permutations that first broke the Enigma in 1932.",
        type: "paper",
      },
      {
        title: "Bletchley Park National Heritage Museum Archive",
        source: "Bletchley Park Trust",
        url: "https://bletchleypark.org.uk/",
        description: "Official educational archive on Hut 8, the Bombe, and the origins of modern computer science.",
        type: "spec",
      },
    ],
    toolId: "enigma",
    glossary: [
      { term: "Rotor", def: "A rotating mechanical disc with 26 electrical contacts on each side connected by internal wiring, creating a dynamic permutation of the alphabet." },
      { term: "Steckerbrett (Plugboard)", def: "A front panel on the Enigma machine that swapped 10 pairs of letters using cross-cables, multiplying key space by ~1.5 × 10¹⁴." },
      { term: "Umkehrwalze (Reflector)", def: "A non-rotating disc at the end of the rotor stack that paired contacts, reflecting electrical current back through the rotors and ensuring E(x) ≠ x." },
      { term: "Turing Bombe", def: "An electro-mechanical computer designed by Alan Turing and Gordon Welchman that searched through rotor combinations by detecting electrical circuit contradictions." },
      { term: "Crib", def: "A suspected plaintext fragment matched against ciphertext to test cryptographic keys or rotor configurations." },
    ],
  },
  {
    id: "baconian",
    trackId: "classical",
    title: "Bacon's cipher & steganography",
    subtitle: "Hiding messages in typography and binary representations",
    formula: {
      expr: "Character → 5-bit binary code (A=aaaaa, B=aaaab, ..., Z=bbaab)",
      badge: "Francis Bacon 1605",
      note: "Each letter is encoded into a 5-symbol permutation of two distinct typefaces or styles. Predates binary computing and ASCII by over three centuries.",
    },
    body: [
      "Invented by English philosopher and statesman Sir Francis Bacon in 1605, Bacon's cipher is an early pioneer of binary representation and steganography. Bacon realized that any alphabet can be encoded using sequences of just two symbols ('a' and 'b'). Since 2⁵ = 32 > 26, a 5-bit code easily represents all Latin letters.",
      "Unlike pure ciphers that scramble text into obvious gibberish, Bacon designed this as a steganographic method — a technique to conceal the very existence of the communication. The 'a' and 'b' symbols were embedded into harmless printed books using two subtly different typefaces (such as normal vs italic, or variations in serif width).",
      "Steganography ('covered writing') complements cryptography: cryptography scrambles a message so adversaries cannot understand it; steganography hides the message so adversaries never suspect it exists. In modern security, steganography is applied to digital media, hiding payload bits in the least significant bits (LSB) of audio or images. However, statistical steganalysis (such as chi-square Pairs of Values analysis) can reliably detect LSB alterations.",
    ],
    keyPoints: [
      "Early 5-bit binary code invented 350 years before the ASCII standard.",
      "Steganography conceals the existence of communication; cryptography conceals its meaning.",
      "Baconian biliteral cipher embeds binary bits into typographical variations (fonts, weights, cases).",
      "Modern digital steganography hides data inside Least Significant Bits (LSBs) of media files.",
    ],
    pitfalls: [
      "Relying on steganography without encryption: once the embedding technique is discovered, the plaintext is exposed in full.",
      "Statistical image analysis (chi-square testing on Pairs of Values) easily detects uniform LSB modifications in carrier images.",
      "Lossy compression (JPEG, MP3) alters low-order bits, destroying fragile LSB steganographic payloads upon re-saving.",
    ],
    workedExample: {
      title: "Encoding 'GO' into Typography via Bacon's 5-Bit Alphabet",
      steps: [
        { label: "1. Lookup Binary Table", detail: "'G' = aabba (00110 in binary). 'O' = abbab (01101 in binary)." },
        { label: "2. Combine Bitstream", detail: "Binary stream for 'GO' = a a b b a a b b a b (length 10)." },
        { label: "3. Prepare Carrier Text", detail: "Take 10-letter carrier sentence: 'K N O W L E D G E S'." },
        { label: "4. Embed via Font Weight", detail: "Map 'a' to lowercase/regular font, 'b' to uppercase/bold font: 'k n O W l e D G e S'." },
        { label: "5. Extraction Verification", detail: "Recipient observes cases: [k, n] = aa, [O, W] = bb, [l] = a → 'aabba' ('G'). [e] = a, [D, G] = bb, [e] = a, [S] = b → 'abbab' ('O'). Plaintext 'GO' is recovered." },
      ],
      outcome: "A casual reader sees standard text; the recipient extracts the bold/plain bits to recover 'GO'.",
    },
    references: [
      {
        title: "Francis Bacon: The Advancement of Learning (1605)",
        source: "Historical Archive",
        url: "https://en.wikipedia.org/wiki/Bacon%27s_cipher",
        description: "Bacon's philosophical text describing the biliteral cipher and font-based message concealment.",
        type: "spec",
      },
      {
        title: "Wikipedia: Steganography and Digital Watermarking",
        source: "Wikipedia",
        url: "https://en.wikipedia.org/wiki/Steganography",
        description: "Comprehensive guide to historical and modern digital steganographic methods.",
        type: "tutorial",
      },
      {
        title: "Niels Provos & Peter Honeyman: Detecting Steganographic Content on the Internet",
        source: "NDSS Symposium",
        url: "https://www.citi.umich.edu/techreports/reports/citi-tr-01-11.pdf",
        description: "Foundational research paper analyzing automated detection of hidden data in millions of JPEG images.",
        type: "paper",
      },
    ],
    toolId: "baconian",
    glossary: [
      { term: "Biliteral Cipher", def: "A cipher using only two symbols or characters (such as 'a' and 'b') to represent an alphabet, functioning as an early binary code." },
      { term: "Steganography", def: "The art and science of hiding communication in such a way that no one apart from the sender and intended recipient suspects the existence of the message." },
      { term: "Carrier Medium (Cover)", def: "The innocent-looking image, text, or audio file within which secret payload data is embedded." },
      { term: "Least Significant Bit (LSB)", def: "The lowest-order bit in an integer or color byte; modifying it creates imperceptible visual or auditory changes in media." },
    ],
  },
];
