import type { Lesson } from "./types";

export const symmetricLessons: Lesson[] = [
  {
    id: "symmetric-basics",
    trackId: "symmetric",
    title: "Symmetric encryption",
    subtitle: "One shared key, used for both directions",
    formula: {
      expr: "E(K, P) = C,  D(K, C) = P,  where K_enc = K_dec = K",
      badge: "Shared Secret",
      note: "Both sender and receiver must share identical secret key K ahead of time. Modern symmetric ciphers encrypt gigabytes per second on hardware AES-NI instructions.",
    },
    body: [
      "Symmetric ciphers are the computational foundation of global cybersecurity, protecting virtually all bulk data at rest (full-disk encryption like BitLocker, LUKS, and FileVault) and data in transit (TLS 1.3 records, SSH sessions, and IPsec VPN tunnels). In a symmetric cryptosystem, the exact same secret key K is utilized for both encryption and decryption. Symmetric algorithms are divided into two fundamental architectures: Block Ciphers, which encrypt fixed-size data blocks (typically 128 bits for AES) using multi-round iterative permutations, and Stream Ciphers, which expand a short secret key and nonce into a continuous pseudorandom keystream XORed with the data.",
      "The Key Distribution Problem: The fundamental limitation of symmetric cryptography is that two parties who have never met must somehow securely exchange key K before sending any encrypted messages. If n participants wish to communicate pairwise securely across a network, they require n(n−1)/2 distinct keys. In a global network of billions of devices, pre-sharing pairwise symmetric keys is an impossible logistical bottleneck. Public-key cryptography (such as Diffie-Hellman and RSA) was invented precisely to solve this problem by establishing a symmetric session key over public channels.",
      "Claude Shannon's Confusion and Diffusion: In his landmark 1949 paper 'Communication Theory of Secrecy Systems', Claude Shannon established the dual design principles that govern all modern symmetric ciphers: 1) Confusion obscures the algebraic and statistical relationship between the secret key and the ciphertext bits, ensuring that changing one bit in the key alters the entire ciphertext unpredictably (achieved via non-linear S-boxes); 2) Diffusion spreads the statistical influence of each individual plaintext bit across the entire ciphertext block, ensuring that linguistic patterns and redundancies in the plaintext are dissipated (achieved via linear permutations and matrix mixing).",
      "The Avalanche Effect: Modern ciphers repeat confusion and diffusion layers across multiple rounds (e.g., 10 to 14 rounds in AES). This creates an exponential avalanche effect: flipping a single bit in the plaintext or the key flips approximately 50% (64 out of 128 bits) of the output ciphertext bits. If an algorithm achieves ideal diffusion, an attacker who observes an encrypted block cannot identify which plaintext bits changed.",
    ],
    keyPoints: [
      "Symmetric cryptography uses one shared secret key for both encryption and decryption.",
      "Extremely fast and computationally lightweight: executes in hardware at multiple gigabytes per second.",
      "Key distribution problem: requires secure out-of-band exchange or asymmetric key agreement (Diffie-Hellman).",
      "Shannon's dual principles: Confusion (non-linear S-boxes) + Diffusion (linear permutations) repeated over rounds.",
      "Strict Avalanche Criterion (SAC): Flipping 1 input bit must flip each output bit with a probability of approximately 0.5.",
    ],
    pitfalls: [
      "Attempting to transmit symmetric keys across unencrypted channels (email, chat, HTTP) without public-key encryption.",
      "Hardcoding symmetric keys in client-side code, mobile binaries, or public source code repositories.",
      "Using short or low-entropy keys (e.g., passwords or MD5 hashes) instead of 128-bit or 256-bit cryptographically secure random keys.",
    ],
    workedExample: {
      title: "Measuring Shannon Avalanche Effect in AES-128",
      steps: [
        { label: "1. Plaintext 1 & 2 (1-Bit Difference)", detail: "P₁ = 0x00000000000000000000000000000000. P₂ = 0x00000000000000000000000000000001 (only the least significant bit is toggled)." },
        { label: "2. Key Selection", detail: "Single 128-bit key K = 0x2b7e151628aed2a6abf7158809cf4f3c." },
        { label: "3. Encrypt Plaintext 1", detail: "C₁ = AES(K, P₁) = 0x66e94bd4ef8a2c3b884cfa59ca342b2e." },
        { label: "4. Encrypt Plaintext 2", detail: "C₂ = AES(K, P₂) = 0xa7a4d538661642878235dc9da3269b2d." },
        { label: "5. Compute Hamming Distance", detail: "XOR difference C₁ ⊕ C₂: exactly 65 out of 128 bits are flipped (50.78%), demonstrating near-perfect Shannon diffusion!" },
      ],
      outcome: "A single flipped input bit completely randomizes the entire 128-bit ciphertext block.",
    },
    references: [
      {
        title: "Claude Shannon: Communication Theory of Secrecy Systems (1949)",
        source: "Bell System Technical Journal",
        url: "https://www.iacr.org/museum/shannon/shannon49.pdf",
        description: "The seminal founding paper introducing confusion, diffusion, and modern symmetric cipher architecture.",
        type: "paper",
      },
      {
        title: "William Stallings: Cryptography and Network Security (8th Edition)",
        source: "Textbook Standard",
        url: "https://en.wikipedia.org/wiki/Symmetric-key_algorithm",
        description: "Chapter 3: Symmetric Ciphers and the Classical Encryption Model.",
        type: "book",
      },
    ],
    toolId: "random-key",
    glossary: [
      { term: "Confusion", def: "A cryptographic property that makes the relationship between the key and the ciphertext as complex and involved as possible." },
      { term: "Diffusion", def: "A cryptographic property that spreads the statistical influence of individual plaintext bits across the entire ciphertext." },
      { term: "Avalanche Effect", def: "A desirable property of cryptographic algorithms where a small change in input produces a significant, unpredictable change in output." },
    ],
  },
  {
    id: "xor",
    trackId: "symmetric",
    title: "XOR, the atom of symmetric crypto",
    subtitle: "Its own inverse, and perfectly balanced",
    formula: {
      expr: "a ⊕ b ⊕ b = a,  P(A ⊕ B = 1 | B uniform random) = 0.5",
      badge: "Involution",
      note: "XOR (Exclusive OR) outputs 1 if and only if the inputs differ. It is an involution (self-canceling) and acts as a perfectly balanced mixing function.",
    },
    body: [
      "The bitwise Exclusive-OR operation (XOR, denoted mathematically by ⊕ and in programming by `^`) is the single most fundamental atomic building block of symmetric cryptography. In digital electronics, XOR outputs 1 if and only if exactly one of its input bits is 1 (modulo-2 addition without carry: 0 ⊕ 0 = 0, 0 ⊕ 1 = 1, 1 ⊕ 0 = 1, 1 ⊕ 1 = 0).",
      "The Perfect Balance Property: If an input bit A (regardless of its probability distribution) is XORed with an independent bit B drawn from a uniform random distribution (where P(B=0) = P(B=1) = 0.5), the resulting output bit C = A ⊕ B is completely uniform and retains zero statistical information about A: P(C = 1) = 0.5. This mathematical fact is the formal proof behind Claude Shannon's theorem on the One-Time Pad: when the key is truly random and never reused, the ciphertext leaks zero mutual information about the plaintext.",
      "The Involution Property: XOR is an algebraic involution, meaning it is its own mathematical inverse: (A ⊕ B) ⊕ B = A ⊕ (B ⊕ B) = A ⊕ 0 = A. This property allows engineers to use the exact same hardware circuit or software instruction for both encryption and decryption! Every stream cipher (ChaCha20, Salsa20, AES-CTR) and one-time pad utilizes XOR to apply keystreams to data.",
      "Critical Warning — Zero Integrity and Malleability: XOR provides confidentiality under a one-time key, but zero cryptographic integrity. Because XOR operates bit-by-bit without cross-bit diffusion, it is completely malleable. If an attacker intercepts ciphertext C = P ⊕ K and wishes to flip bit i in the plaintext from 0 to 1, they simply flip bit i in the ciphertext: C' = C ⊕ Δ. When the recipient decrypts P' = C' ⊕ K = (P ⊕ Δ ⊕ K) = P ⊕ Δ, the targeted bit is modified with 100% mathematical precision without triggering any decryption error.",
    ],
    keyPoints: [
      "XOR is an algebraic involution: applying the key twice cancels out, making encryption and decryption identical.",
      "Mixing with a uniform random bit destroys all statistical correlation (Shannon Perfect Secrecy).",
      "Completely malleable: an attacker can flip arbitrary bits in decrypted plaintext by flipping corresponding ciphertext bits.",
      "Repeating-key XOR is vulnerable to frequency analysis and crib dragging: C₁ ⊕ C₂ = P₁ ⊕ P₂.",
    ],
    pitfalls: [
      "Reusing a one-time pad or stream cipher key: if Key is reused, C₁ ⊕ C₂ = P₁ ⊕ P₂, allowing cryptanalysts to drag common English words across the XOR stream (crib dragging) and recover both plaintexts.",
      "Relying on XOR for authentication or data integrity without an HMAC or AEAD tag.",
    ],
    workedExample: {
      title: "Executing a Bit-Flipping Attack on Unauthenticated XOR",
      steps: [
        { label: "1. Original Plaintext & Ciphertext", detail: "Payment amount: byte 0x30 (ASCII '0'). Key = 0xA5. Ciphertext C = 0x30 ⊕ 0xA5 = 0x95." },
        { label: "2. Adversary Objective", detail: "Attacker intercepts C = 0x95 and wants the recipient bank to read ASCII '9' (0x39). Mask Δ = 0x30 ⊕ 0x39 = 0x09." },
        { label: "3. Tamper Ciphertext", detail: "Attacker modifies ciphertext: C' = C ⊕ Δ = 0x95 ⊕ 0x09 = 0x9C." },
        { label: "4. Bank Decrypts", detail: "Bank computes P' = C' ⊕ Key = 0x9C ⊕ 0xA5 = 0x39 (ASCII '9')! The payment amount changed from $0 to $9 without the attacker ever knowing the key." },
      ],
      outcome: "Proves mathematically why unauthenticated stream ciphers must always be paired with an authentication tag (AEAD).",
    },
    references: [
      {
        title: "Cryptopals Crypto Challenges: Set 1 Challenge 2 & 3",
        source: "Cryptopals",
        url: "https://cryptopals.com/sets/1/challenges/2",
        description: "Hands-on implementation of fixed XOR combinations and single-byte XOR cracking.",
        type: "tutorial",
      },
    ],
    toolId: "xor",
    glossary: [
      { term: "Involution", def: "A function or operator that is its own inverse, such that applying it twice yields the original value." },
      { term: "Malleability", def: "A cryptographic property where an adversary can modify a ciphertext such that it decrypts to a predictable modification of the plaintext." },
    ],
  },
  {
    id: "des-feistel",
    trackId: "symmetric",
    title: "DES and the Feistel network",
    subtitle: "How a weak round function builds a strong cipher",
    formula: {
      expr: "Lᵢ = Rᵢ₋₁,  Rᵢ = Lᵢ₋₁ ⊕ F(Rᵢ₋₁, Kᵢ)  [16 Rounds, 56-bit Key]",
      badge: "NIST FIPS 46-3",
      note: "Feistel networks split the 64-bit block into two 32-bit halves. Decryption uses the identical circuit with the 16 subkeys applied in reverse order, regardless of whether round function F is invertible.",
    },
    body: [
      "Adopted in 1977 by the US National Bureau of Standards (NBS, now NIST), the Data Encryption Standard (DES) served as the world's primary commercial encryption standard for over two decades. Designed by IBM with confidential mathematical input from the National Security Agency (NSA), DES processes 64-bit blocks of data through 16 rounds of a Feistel network parameterized by a 56-bit key (supplied as 64 bits with 8 parity bits).",
      "The Architectural Genius of Horst Feistel: A standard block cipher must be a bijective mathematical permutation (every distinct plaintext block must map to a unique ciphertext block so decryption is possible). However, designing an invertible round function with strong non-linear properties is mathematically difficult. Horst Feistel solved this by splitting the block into two halves (Left L and Right R). In each round, the right half is passed unchanged to become the next left half (L_i = R_{i-1}), while the left half is XORed with the output of a round function F(R_{i-1}, K_i). Because the output of F is simply XORed with L, function F itself does NOT need to be invertible! To decrypt, one simply runs the identical hardware circuit with the round subkeys in reverse order (K₁₆ down to K₁).",
      "The Secret NSA S-Boxes: During DES standardization, IBM's original S-box substitution tables were modified by the NSA without public explanation, sparking intense public suspicion that a backdoor had been inserted. In 1990, Israeli cryptanalysts Eli Biham and Adi Shamir discovered Differential Cryptanalysis—a devastating attack that breaks multi-round block ciphers. When they applied it to DES, they discovered to their amazement that DES was extraordinarily resistant: changing even a single entry in the NSA's S-boxes reduced the cipher's security by orders of magnitude! The NSA had secretly discovered differential cryptanalysis 15 years before academic researchers, and had hardened DES against it.",
      "The Collapse of 56-bit Keys: DES's fatal flaw was not its mathematical architecture, but its short key length: 56 bits corresponds to only 2⁵⁶ ≈ 7.2 × 10¹⁶ possible keys. In 1998, the Electronic Frontier Foundation (EFF) built 'Deep Crack' for $250,000, recovering a DES key in 56 hours. Today, a modern cloud GPU cluster brute-forces a 56-bit DES key in under 15 minutes. Triple DES (3DES) temporarily extended life by applying Encrypt-Decrypt-Encrypt (EDE) with three keys (168 bits), but suffered from the Sweet32 collision vulnerability on its 64-bit blocks and was formally retired by NIST in 2023.",
    ],
    keyPoints: [
      "Feistel networks guarantee mathematical invertibility regardless of whether the internal round function F is invertible.",
      "Decryption uses the identical circuit with round subkeys scheduled in reverse order.",
      "56-bit key length is completely insecure against brute-force hardware attacks.",
      "64-bit block size is vulnerable to Birthday collisions (Sweet32 attack) after encrypting 2³² blocks (approx. 32 GB of data).",
    ],
    pitfalls: [
      "Using Double DES (2DES): 2DES encrypts with two independent 56-bit keys (112 bits total), but the Meet-in-the-Middle attack reduces its effective security to just 2⁵⁷ operations, rendering it barely stronger than single DES.",
      "Using 3DES in modern TLS or VPNs: NIST formally deprecated and withdrew 3DES due to Sweet32 Birthday attacks on 64-bit blocks.",
    ],
    workedExample: {
      title: "One Feistel Round Step-by-Step",
      steps: [
        { label: "1. Block Partition", detail: "64-bit block split into Left half L₀ (32 bits) and Right half R₀ (32 bits)." },
        { label: "2. Pass to Next Left", detail: "L₁ = R₀ (the right half simply moves to the left half)." },
        { label: "3. Expansion Permutation (E-Box)", detail: "R₀ (32 bits) expanded to 48 bits by duplicating 16 border bits." },
        { label: "4. Key Addition", detail: "48-bit expanded block XORed with 48-bit round subkey K₁: E(R₀) ⊕ K₁." },
        { label: "5. S-Box Substitution", detail: "Eight 6-to-4 bit S-boxes substitute 48 bits down to 32 bits, introducing vital non-linear confusion." },
        { label: "6. Permutation (P-Box) & XOR", detail: "32-bit output permuted and XORed with original left half: R₁ = L₀ ⊕ P(S_Box_Output)." },
      ],
      outcome: "Both halves have been thoroughly mixed; applying the same round with K₁ in reverse recovers L₀ and R₀.",
    },
    references: [
      {
        title: "NIST FIPS 46-3: Data Encryption Standard (DES)",
        source: "NIST CSRC Archive",
        url: "https://csrc.nist.gov/publications/detail/fips/46-3/archive/2005-05-19",
        description: "The historical federal standard specifying the 16-round DES algorithm and S-box lookup tables.",
        type: "standard",
      },
      {
        title: "Karthikeyan Bhargavan & Gaëtan Leurent: Sweet32 Birthday Attacks on 64-bit Block Ciphers (2016)",
        source: "ACM CCS 2016",
        url: "https://sweet32.info/",
        description: "The research paper demonstrating real-world CBC collision attacks on 3DES and Blowfish in TLS and OpenVPN.",
        type: "paper",
      },
    ],
    toolId: "des-feistel",
    glossary: [
      { term: "Feistel Cipher", def: "A symmetric block cipher structure where the input block is split in two halves and processed through iterative rounds." },
      { term: "Meet-in-the-Middle Attack", def: "A cryptographic attack that drastically reduces the time complexity of multi-encryption schemes by storing intermediate states." },
    ],
  },
  {
    id: "aes",
    trackId: "symmetric",
    title: "AES, the modern standard",
    subtitle: "SubBytes, ShiftRows, MixColumns, AddRoundKey",
    formula: {
      expr: "Rounds: 10 (128-bit key), 12 (192-bit key), 14 (256-bit key) on 4×4 State Matrix",
      badge: "NIST FIPS 197",
      note: "AES operates on a 128-bit block arranged as a 4×4 matrix of bytes in the Galois Field GF(2⁸) modulo the irreducible polynomial m(x) = x⁸ + x⁴ + x³ + x + 1 (0x11B).",
    },
    body: [
      "In 1997, NIST initiated a five-year global competition to develop the Advanced Encryption Standard (AES) to replace the aging DES. Cryptographers worldwide submitted fifteen competing designs. In October 2000, the Rijndael cipher, engineered by Belgian cryptographers Joan Daemen and Vincent Rijmen, was announced as the winner and standardized in 2001 as NIST FIPS 197.",
      "Architecture: Substitution-Permutation Network (SPN): Unlike DES, AES is not a Feistel cipher. It is a Substitution-Permutation Network operating on a 128-bit block organized as a 4×4 matrix of bytes (the State Matrix). AES executes a parameterized number of rounds depending on key size: 10 rounds for 128-bit keys, 12 rounds for 192-bit keys, and 14 rounds for 256-bit keys. Each round (except the final round, which omits MixColumns) applies four distinct mathematical operations:",
      "1. SubBytes: Non-linear byte substitution. Each byte in the state matrix is replaced with its multiplicative inverse in the finite Galois Field GF(2⁸) modulo irreducible polynomial m(x) = x⁸ + x⁴ + x³ + x + 1 (0x11B), with 0x00 mapped to itself. An affine transformation is then applied over GF(2). This mathematical construction guarantees maximal resistance to both linear and differential cryptanalysis while eliminating simple algebraic relationships.",
      "2. ShiftRows: Linear diffusion step. Row 0 remains unchanged; Row 1 is cyclically shifted left by 1 byte; Row 2 is shifted left by 2 bytes; Row 3 is shifted left by 3 bytes. This ensures that bytes within the same column are dispersed across different columns.",
      "3. MixColumns: Multi-dimensional algebraic diffusion. Each 4-byte column is treated as a four-term polynomial over GF(2⁸) and multiplied modulo (x⁴ + 1) with a fixed maximum distance separable (MDS) matrix. Because the branch number of the MDS matrix is 5, any single-byte change in an input column forces changes in all 4 bytes of the output column.",
      "4. AddRoundKey: Secret key injection. The 128-bit state matrix is bitwise XORed with the corresponding 128-bit round subkey derived from the master key via the AES Key Expansion schedule (utilizing RotWord, SubWord, and round constants Rcon).",
      "Hardware Acceleration & Side Channels: Today, modern CPUs (Intel/AMD AES-NI, ARMv8 Cryptography, Apple M-Series) include dedicated hardware silicon instructions (`aesenc`, `aesdec`) that execute AES round operations in constant clock cycles (under 1 cycle per byte). Hardware execution is critical: software implementations that use precomputed in-memory S-box tables suffer from microarchitectural CPU cache-timing side channels (e.g., Bernstein's cache attack) that leak secret keys across virtual machines.",
    ],
    keyPoints: [
      "Global industry standard operating on 128-bit blocks with 128, 192, or 256-bit key options.",
      "Four atomic round transformations: SubBytes (non-linear confusion), ShiftRows & MixColumns (diffusion), AddRoundKey (key injection).",
      "Mathematical foundation: Finite Galois Field GF(2⁸) arithmetic modulo x⁸ + x⁴ + x³ + x + 1.",
      "Hardware AES-NI execution is mandatory to prevent CPU cache-timing side-channel vulnerabilities.",
    ],
    pitfalls: [
      "Implementing AES in pure C/Python with table lookups for cryptographic operations in multi-tenant cloud environments: cache latency leaks the key.",
      "Confusing block size with key size: AES block size is strictly 128 bits; only the key size varies (128, 192, 256 bits).",
    ],
    workedExample: {
      title: "Tracing the Four Transformations of an AES Round",
      steps: [
        { label: "1. Initial State", detail: "State matrix containing 16 bytes arranged in a 4×4 grid." },
        { label: "2. SubBytes", detail: "State byte 0x53 is inverted in GF(2⁸) and mapped through affine matrix to yield S(0x53) = 0xED." },
        { label: "3. ShiftRows", detail: "Row 0 shifts 0, Row 1 shifts 1 byte left, Row 2 shifts 2 bytes left, Row 3 shifts 3 bytes left, dispersing bytes across columns." },
        { label: "4. MixColumns", detail: "Column [0xED, 0x09, 0x12, 0xAA] multiplied by MDS matrix over GF(2⁸), spreading changes across all 4 output bytes." },
        { label: "5. AddRoundKey", detail: "The entire 128-bit state matrix is XORed with round key K_r derived from key schedule." },
      ],
      outcome: "Provides full non-linear confusion and multi-dimensional diffusion across the entire 128-bit state.",
    },
    references: [
      {
        title: "NIST FIPS 197: Advanced Encryption Standard (AES) Standard (Updated 2023)",
        source: "NIST CSRC",
        url: "https://doi.org/10.6028/NIST.FIPS.197-upd1",
        description: "The official federal publication specifying the AES algorithm, S-box mathematics, and key schedule.",
        type: "standard",
      },
      {
        title: "Joan Daemen & Vincent Rijmen: The Design of Rijndael (AES)",
        source: "Springer Monograph",
        url: "https://en.wikipedia.org/wiki/Advanced_Encryption_Standard",
        description: "The original textbook by the inventors detailing the GF(2⁸) mathematics, wide-trail strategy, and cryptanalytic proofs.",
        type: "book",
      },
    ],
    toolId: "aes-state",
    glossary: [
      { term: "Galois Field GF(2⁸)", def: "A finite field containing 256 elements, where addition is bitwise XOR and multiplication is polynomial multiplication modulo an irreducible polynomial." },
      { term: "AES-NI", def: "A set of hardware microprocessor instructions that accelerate AES encryption and decryption while guaranteeing constant execution time." },
    ],
  },
  {
    id: "modes",
    trackId: "symmetric",
    title: "Modes of operation",
    subtitle: "ECB, CBC, CTR and why GCM won",
    formula: {
      expr: "CBC: Cᵢ = E(K, Pᵢ ⊕ Cᵢ₋₁) | CTR: Cᵢ = Pᵢ ⊕ E(K, Nonce ‖ Counter) | GCM: CTR + GHASH",
      badge: "AEAD Standard",
      note: "Block ciphers only encrypt a single 16-byte block. A mode of operation dictates how sequences of multiple blocks are securely processed.",
    },
    body: [
      "A block cipher like AES-128 is merely a fixed mathematical permutation: it maps a single 16-byte block to a single 16-byte output block. However, real-world data (documents, web pages, videos) spans thousands or millions of bytes. A Mode of Operation specifies the algorithm by which sequences of multiple blocks are securely encrypted. Choosing the wrong mode of operation is responsible for the overwhelming majority of practical symmetric cryptographic breaches in history.",
      "ECB (Electronic Codebook) Mode: The Fatal Trap. ECB divides the plaintext into 16-byte blocks and encrypts each block completely independently using the same key: C_i = E_K(P_i). If the plaintext contains identical 16-byte blocks (such as whitespace, repeated database fields, or image headers), they produce identical ciphertext blocks. This fatal flaw is famously demonstrated by the 'ECB Penguin': encrypting a bitmap image in ECB mode preserves all macroscopic outlines, textures, and silhouettes in plain sight! ECB violates semantic security (IND-CPA) and must never be used under any circumstances.",
      "CBC (Cipher Block Chaining) Mode: In CBC, each plaintext block is XORed with the previous ciphertext block before encryption: C_i = E_K(P_i ⊕ C_{i-1}). To randomize the first block, an unpredictable Initialization Vector (IV) is used as C_0. CBC ensures that identical plaintext blocks encrypt to completely different ciphertexts. However, CBC requires PKCS#7 padding to reach 16-byte block boundaries, introducing devastating Padding Oracle Attacks (Vaudenay 2002, POODLE, Lucky13): if a server reveals whether decrypted padding was valid or invalid, an attacker can decrypt the entire ciphertext byte-by-byte in seconds without ever discovering the key.",
      "CTR (Counter) Mode: CTR turns a block cipher into a stream cipher by encrypting a unique Nonce concatenated with an incrementing integer counter: Keystream_i = E_K(Nonce ‖ Counter_i), and C_i = P_i ⊕ Keystream_i. CTR requires no padding and allows full parallelization across CPU cores. However, reusing a Nonce with the same key allows immediate two-time-pad XOR cancellation: C₁ ⊕ C₂ = P₁ ⊕ P₂.",
      "The Gold Standard: GCM (Galois/Counter Mode). GCM combines the high-speed streaming of CTR mode with a polynomial universal hash function (GHASH) evaluated over the Galois Field GF(2¹²⁸) to generate an unforgeable Authentication Tag. GCM is an Authenticated Encryption with Associated Data (AEAD) standard: it provides Confidentiality, Integrity, and Authenticity simultaneously. Any tampering with the ciphertext causes immediate tag rejection before decryption, permanently eliminating padding oracle vulnerabilities.",
    ],
    keyPoints: [
      "NEVER use ECB mode: identical plaintext blocks leak visual and statistical structures.",
      "CBC requires unpredictable IVs and is vulnerable to padding oracle attacks if authentication is absent.",
      "CTR mode enables high-speed multi-core parallelization, but nonce reuse destroys all confidentiality.",
      "GCM is the modern AEAD standard: always authenticate encrypted data to guarantee integrity.",
    ],
    pitfalls: [
      "Nonce Reuse in AES-GCM (The GCM Forbidden Attack): Reusing a nonce with the same key allows an attacker to compute the GHASH authentication subkey H, completely destroying authenticity and forging arbitrary ciphertexts across past and future sessions.",
      "Using static or predictable sequential IVs in CBC mode (enabling BEAST attacks in TLS 1.0).",
    ],
    workedExample: {
      title: "The Classic Vaudenay CBC Padding Oracle Attack",
      steps: [
        { label: "1. PKCS#7 Padding Rules", detail: "Blocks must end in valid padding bytes: [0x01], [0x02, 0x02], or [0x03, 0x03, 0x03]." },
        { label: "2. Attacker Tampering", detail: "Attacker modifies byte C₁[15] in the ciphertext probe and sends it to the decryption server." },
        { label: "3. Server Leaks Padding Status", detail: "Server decrypts P₂[15] = D_K(C₂)[15] ⊕ C₁[15]. If padding is invalid, server returns HTTP 500; if valid, it returns HTTP 200." },
        { label: "4. Solving the Intermediate Byte", detail: "When HTTP 200 occurs, attacker knows P₂[15] = 0x01. Intermediate byte I[15] = C₁[15] ⊕ 0x01. Plaintext is solved: P₂[15] = I[15] ⊕ Original_C₁[15]." },
      ],
      outcome: "Attacker recovers all plaintext bytes within 256 queries per byte without the encryption key.",
    },
    references: [
      {
        title: "NIST SP 800-38A: Recommendation for Block Cipher Modes of Operation",
        source: "NIST CSRC",
        url: "https://doi.org/10.6028/NIST.SP.800-38A",
        description: "Official federal standard specifying ECB, CBC, OFB, CFB, and CTR modes.",
        type: "standard",
      },
      {
        title: "NIST SP 800-38D: Recommendation for Galois/Counter Mode (GCM)",
        source: "NIST CSRC",
        url: "https://doi.org/10.6028/NIST.SP.800-38D",
        description: "The definitive technical specification for AES-GCM authenticated encryption.",
        type: "standard",
      },
      {
        title: "Serge Vaudenay: Security Flaws Induced by CBC Padding (Eurocrypt 2002)",
        source: "IACR Eurocrypt",
        url: "https://www.iacr.org/cryptodb/data/paper.php?pubkey=1859",
        description: "The landmark paper introducing the padding oracle attack on CBC ciphers.",
        type: "paper",
      },
    ],
    toolId: "block-modes",
    glossary: [
      { term: "Initialization Vector (IV)", def: "A non-secret, unpredictable value used to ensure identical plaintexts encrypt to distinct ciphertexts." },
      { term: "AEAD", def: "Authenticated Encryption with Associated Data: cryptographic primitives providing confidentiality, integrity, and authenticity." },
      { term: "Padding Oracle", def: "A vulnerability where an application reveals whether decrypted padding was valid, allowing complete plaintext recovery." },
    ],
  },
  {
    id: "stream-ciphers",
    trackId: "symmetric",
    title: "Stream ciphers & ARX Quarter-Rounds",
    subtitle: "RC4's fall and ChaCha20's rise",
    formula: {
      expr: "Keystream = ChaCha20(Key, Nonce, Counter)  |  C = P ⊕ Keystream",
      badge: "RFC 8439",
      note: "ChaCha20 uses an ARX (Addition-Rotation-XOR) Quarter-Round on a 512-bit state (16 32-bit words). Eliminates S-box lookup tables, preventing cache-timing attacks completely.",
    },
    body: [
      "Stream ciphers encrypt arbitrary-length data continuous bit-by-bit or byte-by-byte without requiring block padding or cipher block chaining. The most famous early stream cipher, RC4 (designed by Ron Rivest in 1987), was utilized in WEP Wi-Fi, SSL/TLS, and BitTorrent. RC4 used a 256-byte internal permutation array updated via the Key Scheduling Algorithm (KSA) and Pseudo-Random Generation Algorithm (PRGA). However, RC4 suffered from severe initial keystream biases (the Fluhrer-Mantin-Shamir attack and AlFardan-Bernstein attacks): the second output byte had an unacceptably high probability of being 0x00, allowing attackers to recover WEP Wi-Fi keys in minutes by capturing broadcast packets. In 2015, the IETF formally prohibited RC4 across all TLS protocols (RFC 7465).",
      "ChaCha20: Designed by Daniel J. Bernstein (DJB), ChaCha20 is the premier modern stream cipher, standard in TLS 1.3, WireGuard VPN, OpenSSH, and Linux kernel CSPRNGs. It operates on a 512-bit state arranged as a 4×4 matrix of 32-bit words (comprising 4 constant words `'expand 32-byte k'`, an 8-word 256-bit key, a 1-word block counter, and a 3-word 96-bit nonce). The core engine executes 20 rounds of the ARX (Addition, Rotation, XOR) Quarter-Round function.",
      "Why ARX is Revolutionary: Traditional block ciphers like AES rely on non-linear S-box lookup tables. In software running on commodity CPUs without hardware AES-NI instructions, table lookups create memory cache-timing side channels: memory access latency reveals secret key indices to co-located cloud processes. In contrast, ChaCha20 uses only three fundamental CPU instructions: 32-bit integer addition (`+`), bitwise rotation (`<<<`), and bitwise XOR (`^`). Every CPU in existence executes these operations in constant clock cycles, making ChaCha20 completely immune to cache-timing side-channel attacks by design.",
      "ChaCha20-Poly1305 AEAD: Standardized in RFC 8439, ChaCha20 is paired with the Poly1305 one-time polynomial authenticator over the prime field 2¹³⁰ − 5. The first 32 bytes of the ChaCha20 keystream are used as the one-time key for Poly1305, producing a 128-bit authentication tag. On mobile devices, embedded systems, and ARM processors lacking hardware AES engines, ChaCha20-Poly1305 runs three to four times faster than software AES while providing unconditional side-channel immunity.",
    ],
    keyPoints: [
      "RC4 is mathematically broken and prohibited by RFC 7465; NEVER use RC4.",
      "ChaCha20 uses ARX (Add-Rotate-XOR) operations: inherently constant-time and immune to cache timing.",
      "Paired with Poly1305 (RFC 8439) to form the gold-standard AEAD used in WireGuard, TLS 1.3, and Android.",
      "Never reuse a (Key, Nonce) pair: keystream reuse immediately exposes P₁ ⊕ P₂.",
    ],
    pitfalls: [
      "Reusing a Nonce with the same key: XORing two ciphertexts encrypted with the same keystream immediately exposes P₁ ⊕ P₂, allowing automated crib-dragging attacks.",
      "Failing to increment the 32-bit counter block across messages exceeding 256 GB (since 2³² × 64 bytes = 256 GB).",
    ],
    workedExample: {
      title: "Executing the ChaCha20 Quarter-Round Function",
      steps: [
        { label: "1. Quarter-Round Inputs", detail: "Operates on four 32-bit words (a, b, c, d)." },
        { label: "2. Step 1 (Mix a & b into d)", detail: "a += b; d ^= a; d <<<= 16; (Modular addition, XOR, and 16-bit left rotation)." },
        { label: "3. Step 2 (Mix c & d into b)", detail: "c += d; b ^= c; b <<<= 12; (Addition, XOR, and 12-bit left rotation)." },
        { label: "4. Step 3 (Second Mix a & b)", detail: "a += b; d ^= a; d <<<= 8; (Addition, XOR, and 8-bit left rotation)." },
        { label: "5. Step 4 (Second Mix c & d)", detail: "c += d; b ^= c; b <<<= 7; (Addition, XOR, and 7-bit left rotation)." },
      ],
      outcome: "Four simple integer operations mix 128 bits with complete non-linear diffusion in constant clock cycles.",
    },
    references: [
      {
        title: "RFC 8439: ChaCha20 and Poly1305 for IETF Protocols",
        source: "IETF RFC",
        url: "https://www.ietf.org/rfc/rfc8439.txt",
        description: "The definitive standard for ChaCha20 stream cipher and Poly1305 authenticator.",
        type: "standard",
      },
      {
        title: "Daniel J. Bernstein: ChaCha, a variant of Salsa20 (2008)",
        source: "DJB Publications",
        url: "https://cr.yp.to/chacha.html",
        description: "The original paper introducing ChaCha20's diffusion properties and ARX quarter-round design.",
        type: "paper",
      },
    ],
    toolId: "chacha20",
    glossary: [
      { term: "Stream Cipher", def: "A symmetric key cipher where plaintext digits are combined with a pseudorandom cipher digit stream (keystream)." },
      { term: "ARX Architecture", def: "A cryptographic algorithm design paradigm based exclusively on modular Addition, bit Rotation, and XOR." },
    ],
  },
];
