/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttacksRouteImport } from './routes/attacks'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as ForensicsRouteImport } from './routes/forensics'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HandshakeRouteImport } from './routes/handshake'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PqcRouteImport } from './routes/pqc'
import { Route as ZkpRouteImport } from './routes/zkp'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as TracksTrackIdRouteImport } from './routes/tracks.$trackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttacksRoute = AttacksRouteImport.update({
  id: '/attacks',
  path: '/attacks',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsRoute = ForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HandshakeRoute = HandshakeRouteImport.update({
  id: '/handshake',
  path: '/handshake',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PqcRoute = PqcRouteImport.update({
  id: '/pqc',
  path: '/pqc',
  getParentRoute: () => rootRouteImport,
} as any)
const ZkpRoute = ZkpRouteImport.update({
  id: '/zkp',
  path: '/zkp',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksTrackIdRoute = TracksTrackIdRouteImport.update({
  id: '/tracks/$trackId',
  path: '/tracks/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/benchmark': typeof BenchmarkRoute
  '/challenges': typeof ChallengesRoute
  '/flashcards': typeof FlashcardsRoute
  '/forensics': typeof ForensicsRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/handshake': typeof HandshakeRoute
  '/matrix': typeof MatrixRoute
  '/notebook': typeof NotebookRoute
  '/pipeline': typeof PipelineRoute
  '/pqc': typeof PqcRoute
  '/zkp': typeof ZkpRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/benchmark': typeof BenchmarkRoute
  '/challenges': typeof ChallengesRoute
  '/flashcards': typeof FlashcardsRoute
  '/forensics': typeof ForensicsRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/handshake': typeof HandshakeRoute
  '/matrix': typeof MatrixRoute
  '/notebook': typeof NotebookRoute
  '/pipeline': typeof PipelineRoute
  '/pqc': typeof PqcRoute
  '/zkp': typeof ZkpRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attacks': typeof AttacksRoute
  '/benchmark': typeof BenchmarkRoute
  '/challenges': typeof ChallengesRoute
  '/flashcards': typeof FlashcardsRoute
  '/forensics': typeof ForensicsRoute
  '/glossary': typeof GlossaryRoute
  '/guide': typeof GuideRoute
  '/handshake': typeof HandshakeRoute
  '/matrix': typeof MatrixRoute
  '/notebook': typeof NotebookRoute
  '/pipeline': typeof PipelineRoute
  '/pqc': typeof PqcRoute
  '/zkp': typeof ZkpRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/tools/$toolId': typeof ToolsToolIdRoute
  '/tracks/$trackId': typeof TracksTrackIdRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attacks'
    | '/benchmark'
    | '/challenges'
    | '/flashcards'
    | '/forensics'
    | '/glossary'
    | '/guide'
    | '/handshake'
    | '/matrix'
    | '/notebook'
    | '/pipeline'
    | '/pqc'
    | '/zkp'
    | '/lessons/$lessonId'
    | '/tools/$toolId'
    | '/tracks/$trackId'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attacks'
    | '/benchmark'
    | '/challenges'
    | '/flashcards'
    | '/forensics'
    | '/glossary'
    | '/guide'
    | '/handshake'
    | '/matrix'
    | '/notebook'
    | '/pipeline'
    | '/pqc'
    | '/zkp'
    | '/lessons/$lessonId'
    | '/tools/$toolId'
    | '/tracks/$trackId'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/attacks'
    | '/benchmark'
    | '/challenges'
    | '/flashcards'
    | '/forensics'
    | '/glossary'
    | '/guide'
    | '/handshake'
    | '/matrix'
    | '/notebook'
    | '/pipeline'
    | '/pqc'
    | '/zkp'
    | '/lessons/$lessonId'
    | '/tools/$toolId'
    | '/tracks/$trackId'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttacksRoute: typeof AttacksRoute
  BenchmarkRoute: typeof BenchmarkRoute
  ChallengesRoute: typeof ChallengesRoute
  FlashcardsRoute: typeof FlashcardsRoute
  ForensicsRoute: typeof ForensicsRoute
  GlossaryRoute: typeof GlossaryRoute
  GuideRoute: typeof GuideRoute
  HandshakeRoute: typeof HandshakeRoute
  MatrixRoute: typeof MatrixRoute
  NotebookRoute: typeof NotebookRoute
  PipelineRoute: typeof PipelineRoute
  PqcRoute: typeof PqcRoute
  ZkpRoute: typeof ZkpRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  ToolsToolIdRoute: typeof ToolsToolIdRoute
  TracksTrackIdRoute: typeof TracksTrackIdRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attacks': {
      id: '/attacks'
      path: '/attacks'
      fullPath: '/attacks'
      preLoaderRoute: typeof AttacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics': {
      id: '/forensics'
      path: '/forensics'
      fullPath: '/forensics'
      preLoaderRoute: typeof ForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handshake': {
      id: '/handshake'
      path: '/handshake'
      fullPath: '/handshake'
      preLoaderRoute: typeof HandshakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pqc': {
      id: '/pqc'
      path: '/pqc'
      fullPath: '/pqc'
      preLoaderRoute: typeof PqcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zkp': {
      id: '/zkp'
      path: '/zkp'
      fullPath: '/zkp'
      preLoaderRoute: typeof ZkpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$trackId': {
      id: '/tracks/$trackId'
      path: '/tracks/$trackId'
      fullPath: '/tracks/$trackId'
      preLoaderRoute: typeof TracksTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttacksRoute: AttacksRoute,
  BenchmarkRoute: BenchmarkRoute,
  ChallengesRoute: ChallengesRoute,
  FlashcardsRoute: FlashcardsRoute,
  ForensicsRoute: ForensicsRoute,
  GlossaryRoute: GlossaryRoute,
  GuideRoute: GuideRoute,
  HandshakeRoute: HandshakeRoute,
  MatrixRoute: MatrixRoute,
  NotebookRoute: NotebookRoute,
  PipelineRoute: PipelineRoute,
  PqcRoute: PqcRoute,
  ZkpRoute: ZkpRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  ToolsToolIdRoute: ToolsToolIdRoute,
  TracksTrackIdRoute: TracksTrackIdRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
